### ISSUE TITLE
First Party Release Package DLL's Not Signed Only Exe's

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#107]
**Describe the bug**
Goal is to sign executable binary files for CLI and GUI release packages for Windows.  Currently only the .exe's are signed due to build pipeline configuration.

**To Reproduce**
1. Download release zips for Windows
2. See file properties for .exe's with signature
3. See file properties for first party (this project) .dll's without a digital signature

**Expected behavior**
See description

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: latest
 - CLI or GUI: both

**Additional Context**

**Comment by gfs** [comment]
Fixed as of Build 99.
