### ISSUE TITLE
Add Verifiable Signature to Hashes File

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#108]
**Is your feature request related to a problem? Please describe.**
Users should have a way to verify the hashes found in hashes.txt match those in the downloadable asset packages and that they haven't been tampered with.

**Describe the solution you'd like**
Add a GPG based or similar signature for the hashes file now included in each Release that can be used to verify against Release zip/tar packages that are part of the automated build pipeline.

**Comment by gfs** [comment]
Completed. Needs documentation for how to validate the signature.

**Comment by Guydalf** [comment]
An early version of the instructions is posted on the Wiki section of the project titled Verifying Signatures and Hashes.  It's functional but is lacking the public key needed to ensure the hashes.txt has not been modified.  We are currently revisiting which key we want to use for final product signing and will publish this asap.
