### ISSUE TITLE
Use known Security IDs in SDDL dump

### ISSUE THREAD

**Issue by FritzSandsTM** [microsoft/AttackSurfaceAnalyzer#118]
The comparison output file displays the SDDL permissions string for any new or modified file.  The string contains security IDs, but only in their raw form.  The report would be much more readable if the security IDs, if possible, were output using their well-known-SID name.  "Everone", "IID_USR", "Administrators", etc.

**Comment by gfs** [comment]
There appears to be no included API in .NET Core for converting the SSDL form to anything more human legible.  

There are various ways to do this. 
Powershell: https://github.com/canix1/SDDL-Converter. 
Perl: https://metacpan.org/release/Win32-SDDL/source/lib/Win32/SDDL.pm
Ssdl.h: https://docs.microsoft.com/en-us/windows/desktop/api/Sddl/nf-sddl-convertstringsecuritydescriptortosecuritydescriptora

Based on observed performance overhead of calling out to powershell the most promising is using ConvertStringSecurityDescriptorToSecurityDescriptor

**Comment by FritzSandsTM** [comment]
Yeah, ConvertStringSecurityDescriptorToSecurityDescriptor is a good approach for Windows.  Are there equivalents for MacOS and Linux?  (I am a complete novice on those OS'es).  And all Powershell would do is call into the same OS API anyways.

**Comment by FritzSandsTM** [comment]
On ASA 1.0 we rolled our own conversion, but that was because of a design requirement -- that analysis could take place on a machine with a downlevel operating system -- so we could not rely on the system API set.

**Comment by gfs** [comment]
For Linux we already gather the mapping between user ids and names. Each file only has one owner and one group. The only official 'well-known' identity is root @ 0. https://stackoverflow.com/questions/1013516/what-are-the-well-known-uids says you can check ```/etc/login.defs``` to see what sections are "User accounts" vs "Service accounts". I know at least on  ubuntu the first user account is always 1000.

For mac, similarly we already gather the mappings between uid and username already.

Good context for ASA.
