### ISSUE TITLE
Make it clear where the output artifacts land

### ISSUE THREAD

**Issue by goldstar611** [Microsoft/AttackSurfaceAnalyzer#129]
**Describe the bug**
The output.html file is created in the same directory as the cli executable instead of the "Output" directory. This was confused me because I didn't know what I was looking for after ASA said it completed successfully. (There is no mention in the console of what ASA does when you run with the compare option)

**To Reproduce**
1. git clone && build the Cli in release mode
1. Navigate to the Cli release Linux folder
1. run sudo ./AttackSurfaceAnalyzerCli collect -a
1. << Install something >>
1. run sudo ./AttackSurfaceAnalyzerCli compare -a
1. figure out what artifacts were dropped by the compare option

**Expected behavior**
All artifacts go in the "Output" directory

**Screenshots**

![image](https://user-images.githubusercontent.com/13027044/56384722-be04ce80-61e2-11e9-9aba-aae4ac99d3a0.png)

**System Configuration (please complete the following information):**
 - OS: Ubuntu 16.04
 - OS Ubuntu 16.04.6 (XFCE desktop)
 - Application Version: master @ 99df9b38786c0e7c94c1e26d397cc1af5758467e
 - CLI or GUI: Cli

**Additional Context**
There is one file in the "Output" directory called "Output.cshtml"

**Comment by gfs** [comment]
Thanks for this report. I understand that is a bit confusing and I'll add some clarification.  The Output.cshtml file is used to render the output.html, and should really be an embedded resource, i'll tie cleaning that up to this.
