### ISSUE TITLE
Help menu has unused items on Linux GUI

### ISSUE THREAD

**Issue by goldstar611** [Microsoft/AttackSurfaceAnalyzer#134]
**Describe the bug**
Attempting to visit any of the items in the "Help" menu from ASA Gui results in either documentation being run as root or (if using firefox) web browser refusing to run.

```
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/user which is owned by user.)
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/user which is owned by user.)
```
**To Reproduce**
1. Run ASA Gui as root
2. Click on Help -> {Learn More, Documentation, Community discussions, Search Issues}
3. Browser either runs as root or browser refuses to load
4. See error in console

**Expected behavior**
Web browser links are run as non-root

**Screenshots**
N/A

**System Configuration (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 16.04.6 with XFCE + FireFox
 - Application Version: 2.0.109-beta+99df9b3878
 - CLI or GUI: Gui

**Additional Context**

**Comment by gfs** [comment]
The help menu shouldn't be populated, we haven't set anything up for those endpoints, must be part of the template that wasn't presenting on the other platforms.

**Comment by gfs** [comment]
@goldstar611 Was this on a debug or a production build? (electronize start vs electonize build)

**Comment by goldstar611** [comment]
I was using ```electronize start``` command to bring up the GUI

**Comment by gfs** [comment]
Okay. I think we don't have an issue here after all.  ```electronize start``` will start the electron application in debug mode, in which it shows the menu bar.  On the release builds there shouldn't be any items in the menu bar. To get a release build use ```electronize build /target linux```.  If you still see the same behavior on release builds we do have an issue to address.
