### ISSUE TITLE
Export feature in GUI app non-responsive

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#158]
**Describe the bug**
Create two scans and run the results analysis.  Use the export button and nothing happens.

**To Reproduce**
1. Select a results filter i.e. users, services etc. and see the results view populated and the Export button become enabled.
2. Enter a path e.g. c:\temp or select one through the folder open UI option
3. Select the export selected or all results option (one) 
4. Select the export button -nothing happens.  No output is generated nor is there any error or other type of message.  It simply doesn't work.

**Expected behavior**
1. The export feature should default to one of the optional radio controls being selected at the since the Export button is enabled OR it should not enable until the user selects one.
2. If the user fails to enter a path or select a folder the export button should not be enabled
3. If the user enters an invalid path or selects a valid one only to have that folder disappear or become invalid after launching the export the user should see an invalid folder message to check it again etc.
4. If the user completes an export, they should see a message box indicating the export is successful.

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: Windows (others not tested but may be applicable)
 - OS Version: 10
 - Application Version: 
 - CLI or GUI:  GUI

**Additional Context**

**Comment by gfs** [comment]
It looks like the Export button isn't being properly triggered to be enabled.

**Comment by gfs** [comment]
Fixed in #159.
