### ISSUE TITLE
Update the ASA Wikipedia page with information on the new release

### ISSUE THREAD

**Issue by scovetta** [Microsoft/AttackSurfaceAnalyzer#16]
**Describe the solution you'd like**
The public [Wikipedia page](https://en.wikipedia.org/wiki/Attack_Surface_Analyzer) should be updated to include information on the new version, but leaving some information on the original version, too.

**Comment by Guydalf** [comment]
Updated to clarify project is current at a Preview-release stage and updated existing text identifying classic 1.0 version of tool for clarity -see Why Attack Surface Analyzer section.
