### ISSUE TITLE
Document how to validate the signature on the hashes file

### ISSUE THREAD

**Issue by gfs** [microsoft/AttackSurfaceAnalyzer#160]
Follows up from #108. We need documentation for how end users could validate the pgp signature on the hashes file if they desired to do so.

**Comment by beerisgood** [comment]
Any news?

If i try to check the HASHES.txt, Kleopatra told me that the Key ID is 0xB4FF1B5F513B22CC but i can't get it nor can check the fingerprint somewhere.
The Key and Fingerprint should be uploaded to this repository

**Comment by gfs** [comment]
@guydalf

**Comment by Guydalf** [comment]
Right.  Will provide by end of day.

**Comment by Guydalf** [comment]
An early version of the instructions is posted on the Wiki section of the project titled Verifying Signatures and Hashes.  It's functional but is lacking the public key needed to ensure the hashes.txt has not been modified.  We are currently revisiting which key we want to use for final product signing and will publish this asap.

**Comment by gfs** [comment]
@Guydalf any update?

**Comment by gfs** [comment]
We no longer sign the hash file.
