### ISSUE TITLE
Deleted Certificates Identified As Created

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#171]
**Describe the bug**
Delete a certificate (export first) after taking a baseline snapshot.  Run another and compare and note the deletion is mislabeled as a **created** change and that user can not expand to see the details for it. Also note the total records count is off -see image. 

Reimport the certificate and run another snapshot to compare and note the creation is reported as created correctly and details can now be expanded.  Affects only the GUI version, the CLI seems to work.

**To Reproduce**
1. Create a baseline scan with just certificates selected
2. Go to user certificate manager (Windows)
3. Find a certificate, export it, delete it.
4. Run another similar scan and compare and note no changes are detected
5. Import the original cert and run another scan.  Note the addition is detected.

**Expected behavior**
Should label the deletions properly as deleted not created.  Total records count should be accurate.  shows 3 when only one is shown.  Also the expand option doesn't work all the time...even on adding certs back.  Sometimes works.  I've added another saved screenshot where it did expand between the last delete and reimport.

**Screenshots**

![deletedcertsayscreated](https://user-images.githubusercontent.com/47648296/57001529-feaf0100-6b6d-11e9-8ab2-4a34d99beaec.png)
![deletedcertsayscreated2](https://user-images.githubusercontent.com/47648296/57003601-c6fb8580-6b7c-11e9-9335-fcd14e1ec0a2.png)
![deletedcertsayscreated3countoff](https://user-images.githubusercontent.com/47648296/57003696-5012bc80-6b7d-11e9-8517-91ed9c90da41.png)
![addcertsback](https://user-images.githubusercontent.com/47648296/57003699-52751680-6b7d-11e9-827c-8bc6efaa0a42.png)
![addcertsbackexpandedworks](https://user-images.githubusercontent.com/47648296/57003881-be0bb380-6b7e-11e9-9981-8c7562ed6f05.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - Application Version: see image
 - CLI or GUI: GUI only

**Additional Context**

**Comment by gfs** [comment]
Suspect just a simple copy/paste error when entering strings.

**Comment by gfs** [comment]
Can you attach the json?
