### ISSUE TITLE
RunId values with whitespace leading app hang or to UX issues

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#174]
**Describe the bug**
A user may quickly generate an id without noting whitespace while entered leading to duplicate ID's from a visual standpoint and actually hang the application by using an id of pure whitespace requiring a manual restart.

**To Reproduce**
1. Go to Scan page and enter the id "1" and complete the scan
2. Enter a new scan id of "1 ", another as "1     " and complete the scans
3. Generate a few others using what label is wanted
4. On the Results page use the drop down and note it is not possible to distinguish between "1", "1 ", and "1    "
While this is not realistic per se a user can easily reproduce the same issue using something like "myscan" vs "myscan  " etc.

Additional error (related and same fix) is if the user enters " " as the runid the application will actually hang requiring manual termination and restart.

**Expected behavior**

**Screenshots**
![notrimid](https://user-images.githubusercontent.com/47648296/57002030-218ee480-6b71-11e9-8dfc-ac7f04961108.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Application Version: 2.1...see image
 - CLI or GUI: GUI only.  CLI is unaffected.

**Additional Context**

**Comment by gfs** [comment]
Good catch. Should be stripping leading and trailing whitespaces.
