### ISSUE TITLE
Export Button Enabled with No Path Selected

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#178]
**Describe the bug**
Export As JSON button is enabled without the user specifying a path via the text control or folder selection button which combined with no invocation or completion message the user leaves them unclear if something is required or broken because the default path shown does appear to be valid e.g. c:\users\[userid]\Documents.

Note a different behavior with the Live monitoring Export to JSON in that a default is provided and is used i.e. c:\ so that the user does not need to enter anything.

**To Reproduce**
1. Go to Results page and select Run Analysis with valid results to export
2. Note the path text control has what looks like a valid path and may assume Export is ready for use and click the enabled Export to JSON button.
3. No export is initiated because a required value for the path is not indicated via user interaction or visible UI.

**Expected behavior**
Either disable the Export button until all required fields including the export path are filled or inform the user of the missing value on an attempt to use it.

**Screenshots**
![ExportNoPathEntered](https://user-images.githubusercontent.com/47648296/57002626-96fcb400-6b75-11e9-9a49-9eb390bc0d0e.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Application Version: 2.1.4-alpha
 - CLI or GUI: GUI only

**Additional Context**

**Comment by gfs** [comment]
Nothing is being exported because you haven't selected a radio button. The placeholder value there will correctly be used.
