### ISSUE TITLE
Add Application Version to Export JSON for Support

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#179]
**Is your feature request related to a problem? Please describe.**
It's always a good idea to include the version of the tool that generated an output for support reasons to trace it back etc.  There is no way to tell that today.

**Describe the solution you'd like**
Add a meta data section header to the structure to include any app data like version.

**Describe alternatives you've considered**
None because it really has to go with the data file.

**System Configuration (please complete the following information):**
* OS: Windows
* OS Version: [e.g. Windows 10 1803]
* Application Version: [e.g. 2.0.1-beta+50af283871]
* CLI or GUI: All

**Additional context**

**Comment by gfs** [comment]
Great suggestion.
