### ISSUE TITLE
Run Status Label Location should be scooched down

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#180]
**Is your feature request related to a problem? Please describe.**
Just a UI nit.  The Run Status label on the Configure Scan page is sitting alone and vertically not aligned with anything on the left.

**Describe the solution you'd like**
Suggest to move it down above the status report details or consider moving results up higher and adding a visible vertical divider between left and right sections whereas the results appear to be centered vertically.

**Describe alternatives you've considered**
Yes two options are mentioned

**System Configuration (please complete the following information):**
* OS: Windows
* OS Version: [e.g. Windows 10 1803]
* Application Version: 2.1.4-alpha
* CLI or GUI: GUI

**Additional context**
![RunStatusLabel](https://user-images.githubusercontent.com/47648296/57002783-c6f88700-6b76-11e9-869f-642fdf7a880c.png)

**Comment by gfs** [comment]
Noted. Can scrunch that down a bit.
