### ISSUE TITLE
Improved Clarity in Expanded Results for Services

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#182]
**Is your feature request related to a problem? Please describe.**
Users that choose to expand the results section for the services filter and a selected entry have to already know or verify manually to know what the before vs after state was.  Combined with the summary value not showing the present but the before state and this can be less effective than it could.

**Describe the solution you'd like**
The results details clarity could be improved by adding a before and after set of column labels in the expanded section to help in the GUI app.  CLI results are very clear i.e. Before vs After etc.  See attached.

**Describe alternatives you've considered**

**System Configuration (please complete the following information):**
* OS: Windows
* OS Version: [e.g. Windows 10 1803]
* Application Version: 2.1.4-alpha
* CLI or GUI: GUI only

**Additional context**
![servicedetailsclarity](https://user-images.githubusercontent.com/47648296/57003189-d9c08b00-6b79-11e9-9aff-821f4b3fa651.png)
![cmdservices](https://user-images.githubusercontent.com/47648296/57003213-f066e200-6b79-11e9-89aa-8d7ed7a5441f.png)

**Comment by gfs** [comment]
Thanks for the suggestion guy. I thought those tables would align properly but it looks like not. I can add headers rename currentstate to runningstate.

**Comment by gfs** [comment]
![image](https://user-images.githubusercontent.com/98900/57172258-606fa500-6dd2-11e9-8200-1bfab8f384e9.png)
I changed the GUI display page so the context for the result info is clearer
