### ISSUE TITLE
Home page date appears to have static value of 2/28/19

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#183]
**Describe the bug**
I haven't checked code but the date should be advancing and appears to be static with an older date that doesn't reflect the latest on master etc.  The "2.0-preview" value may also need to be checked.

**To Reproduce**
1. Go to GUI home page and see "2/28/19" date and "2.0-preview" values.

**Expected behavior**
Users should be informed of a later version of the application being available on each home page load if I understand the intent.

**Screenshots**
![staticdate](https://user-images.githubusercontent.com/47648296/57003398-5d2eac00-6b7b-11e9-9dc1-2f3a12c4e7e1.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment]
I'll update the static value to our official release date when we have one. I'm not exploring dynamically populating that at this time.
