### ISSUE TITLE
Certificate Completed Status Shows No Results but Count of 1

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#184]
**Describe the bug**
Between two scans for certificate changes I had one result where the analysis shows a change detected and a total count of 1 but no results appear in the results area.  Note that certificates is selected in the filter.

**To Reproduce**
1. Remove a certificate and add it back in between two scans
2. Click on the Results and Run Analysis
3. See error in attached

**Expected behavior**
A detailed record to observe in the results area

**Screenshots**
![1countNocertResults](https://user-images.githubusercontent.com/47648296/57003825-3d4cb780-6b7e-11e9-927e-9318adb68f40.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Application Version: 2.1.4-alpha
 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment]
Can you attach a json export of this certificate collection?

**Comment by Guydalf** [comment]
[deletedcert5_vs_deletedcert6_summary.json.txt](https://github.com/Microsoft/AttackSurfaceAnalyzer/files/3134966/deletedcert5_vs_deletedcert6_summary.json.txt)
[deletedcert5_vs_deletedcert6_CERTIFICATE.json.txt](https://github.com/Microsoft/AttackSurfaceAnalyzer/files/3134967/deletedcert5_vs_deletedcert6_CERTIFICATE.json.txt)

**Comment by gfs** [comment]
Can reproduce this.
