### ISSUE TITLE
Javascript errors on Win GUI launch

### ISSUE THREAD

**Issue by Guydalf** [microsoft/AttackSurfaceAnalyzer#195]
**Describe the bug**
The 2.0.138 build when launching the GUI throws up a JavaScript error that is blocking -app does not start.  See screenshot.

**To Reproduce**
1. Go to asa.exe
2. Click on asa.exe using Admin role
3. See error

**Expected behavior**

**Screenshots**

![JSErrOnLaunch](https://user-images.githubusercontent.com/47648296/57335786-96fe3600-70d8-11e9-9298-215d2320d072.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: 2.0.138.x (release)
 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment]
Fixed in 141. Appears to have been a transient issue with Azure Pipelines.
