### ISSUE TITLE
config --list-runs not firing in CLI

### ISSUE THREAD

**Issue by BradyDonovan** [microsoft/AttackSurfaceAnalyzer#207]
**Describe the bug**
Was looking to see previous runs with `config --list-runs` but it doesn't seem to be firing. It's failing the `DatabaseManager.IsFirstRun()` check (always seems to be true from `_firstRun` set?), so it always returns `This appears to be the first run with database asa.sqlite. There are no runs to list.`.

**To Reproduce**
1. Run any two collections.
2. Run `AttackSurfaceAnalyzerCli.exe config --list-runs`

**Expected behavior**
Expecting the check to pass and list previous runs.

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 1903
 - Application Version: 2.1.15-alpha+d0538042e1
 - CLI or GUI: CLI

**Additional Context**

**Comment by gfs** [comment]
Thanks for the report Brady. I'll take a look this evening.

**Comment by gfs** [comment]
I tested the official release (2.0.141) and it doesn't exhibit this behavior.

I was able to repro on the master branch. Fix available in #208.
