### ISSUE TITLE
ASA attempts to download entire OneDrive repository to disk

### ISSUE THREAD

**Issue by riverar** [microsoft/AttackSurfaceAnalyzer#211]
When running an ASA scan (filesystem collector), ASA triggers the download of every file in a user's OneDrive account, potentially filling up the entire disk.

**To Reproduce**
1. Configure Windows account with a Microsoft OneDrive account
2. Ensure "Save space and download files as you use them" is enabled in Settings
3. Start ASA scan
4. Observe flurry of OneDrive activity

**Expected behavior**
ASA to skip cloud-specific reparse points.

**System Configuration:**
 - OS: Windows 10
 - OS Version: 18362.113
 - Application Version: asagui-windows-2.0.143
 - CLI or GUI: gui

**Comment by scovetta** [comment]
Yikes! Thanks for the report, @riverar!

I image this could happen with Dropbox, and others, plus Git/GVFS, similar -- It seems like these files could have attributes like [FILE_ATTRIBUTE_REPARSE_POINT](https://docs.microsoft.com/en-us/windows/desktop/FileIO/file-attribute-constants), FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS, FILE_ATTRIBUTE_SPARSE_FILE, FILE_ATTRIBUTE_OFFLINE, etc., which unfortunately don't seem to be exposed via .NET Core, so we might have to go to an OS-specific check on Windows, and dig into what to do on Linux and macOS.

**Comment by gfs** [comment]
I already skip everything marked as a RESPARE_POINT to skip symlinks so we don't hit loops, so OneDrive must be using another mechanism.

Thanks for the report. A fix for this will be pushed to the 2.0 branch.

**Comment by riverar** [comment]
Thanks @scovetta @gfs. The directories and files have reparse tags but you're right, they're specially not marked specifically as reparse points. (They rely on pinned/unpinned attributes to indicate physicality on disk.)

I'm not familiar with the overall architecture or goals of ASA, so it's unclear if this presents an area of possible "hidden change". For a tool that is relied upon to report changes anywhere and everywhere, this could be a critical blindspot.

If that's not a concern, a back of the napkin fix could be to do something like this:

```diff
 namespace AttackSurfaceAnalyzer.Utils
 {
     public class DirectoryWalker
-    {
+    {
+        private enum FileAttributesEx
+        {
+            FILE_ATTRIBUTE_UNPINNED = 0x00100000,
+            FILE_ATTRIBUTE_RECALL_ON_OPEN = 0x00040000,
+            FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS = 0x00400000
+        }
+
         public static IEnumerable<FileSystemInfo> WalkDirectory(string root)
         {
             // Data structure to hold names of subfolders to be
@@ -125,6 +132,12 @@ namespace AttackSurfaceAnalyzer.Utils
                             Log.Verbose("Skipping symlink {0}", str);
                             continue;
                         }
+
+                        if (!IsPhysicallyPresent(fileInfo))
+                        {
+                            Log.Verbose("Skipping virtual directory {0}", str);
+                            continue;
+                        }                                                                                                                   }
                     catch (System.IO.DirectoryNotFoundException e)
                     {
@@ -148,5 +161,12 @@ namespace AttackSurfaceAnalyzer.Utils
                 }
             }
         }
+
+        private static bool IsPhysicallyPresent(FileSystemInfo fileSystemInfo)
+        {
+            return !(fileSystemInfo.Attributes.HasFlag(FileAttributesEx.FILE_ATTRIBUTE_UNPINNED) ||
+                fileSystemInfo.Attributes.HasFlag(FileAttributesEx.FILE_ATTRIBUTE_RECALL_ON_OPEN) ||
+                fileSystemInfo.Attributes.HasFlag(FileAttributesEx.FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS));
+        }
     }
 }
```

**Comment by gfs** [comment]
Hey @riverar thanks so much for this proposed patch!

I'm leaning towards skipping these files by default and adding a cli argument to include them. This is in line with other behavior we have to skip because they have system only permissions (C:\pagefile.sys) or are otherwise too noisy to be useful.

**Comment by gfs** [comment]
It looks like this proposed method won't work. Unfortunately Attributes.HasFlag checks the type of the enum passed in and requires it to be a System.IO.FileAttributes which does not have the Pinned attribute as one of its options.

An alternate method for doing this is to call out to ATTRIB.exe or use Powershell (which I'll investigate). But it looks like this isn't built into .NET Core.

**Comment by riverar** [comment]
I'd just break fileSystemInfo.Attributes down and do the check yourself.
(e.g. `((uint)fileSystemInfo.Attributes) & FILE_ATTRIBUTE_UNPINNED) != 0` )

**Comment by gfs** [comment]
Alas, the attributes in filesysteminfo.attributes appear to be actually limited to the enums in System.IO.FileAttributes, rather than being backed by the "true", more elaborate state of the flags.

**Comment by gfs** [comment]
Looks like the best approach is to P/Invoke [GetFileAttributesExA](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getfileattributesexa).

**Comment by riverar** [comment]
@gfs Isn't clear why you couldn't just use FileSystemInfo.Attributes like demonstrated above. Am I missing something?

**Comment by gfs** [comment]
I tried. .net core exposes a managed cross platform enum with limited fields. Not the underlying properties field.
