### ISSUE TITLE
AttackSurfaceAnalyzer-GUI.exe crashes on startup

### ISSUE THREAD

**Issue by SteffanH** [microsoft/AttackSurfaceAnalyzer#212]
**Describe the bug**
Double-clicking the asa.exe file results in two asa.exe processes, but no GUI is shown

**To Reproduce**
1. Download& extract AsaGui-win10-2.1.19.zip
2. Double click on "asa.exe"
3. Go to event viewer

> Application: AttackSurfaceAnalyzer-GUI.exe
> CoreCLR Version: 4.6.27521.2
> Description: The process was terminated due to an unhandled exception.
> Exception Info: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'near "-": syntax error'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
>    at AttackSurfaceAnalyzer.Utils.DatabaseManager.Setup() in D:\a\1\s\Lib\Utils\DatabaseManager.cs:line 98
>    at AttackSurfaceAnalyzer.Gui.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\a\1\s\Gui\Startup.cs:line 43
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
>    at AttackSurfaceAnalyzer.Gui.Program.Main(String[] args) in D:\a\1\s\Gui\Program.cs:line 14
> 

**Expected behavior**
I would have expected the GUI to show.

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Enterprise Insider Preview Version 1903 (OS Build 18898.1000)
 - Application Version: 2.1.19
 - CLI or GUI: GUI

**Comment by SteffanH** [comment]
v2.0.143 launches OK

**Comment by gfs** [comment]
Fixed in #217. Fix available in 2.1.20 and later.
