### ISSUE TITLE
[Request] Add ability to stop collectors mid run

### ISSUE THREAD

**Issue by Oleg26Dev** [microsoft/AttackSurfaceAnalyzer#224]
How to cancel a long operation ? 
For example, I see that 'FileSystemCollector is Running' works long and I want to cancel it.

**Comment by gfs** [comment]
There is no built in mechanism to stop a collector at this time.

**Comment by gfs** [comment]
Closing this as fixed with #343. Both CLI and GUI are now run from the console.  Press CTRL+C to cancel your long running collection operation and ASA will gracefully quit without corrupting your database.
