### ISSUE TITLE
hostfxr.dll failure

### ISSUE THREAD

**Issue by DigiAngel** [microsoft/AttackSurfaceAnalyzer#225]
Just trying this out..this is Win7 64 bit SP1, vc runtime 2015 update 3 is installed as well as .NET Core 2.2 runtime.  Here's what I get when I try and run:

~~~
Failed to load the dll from [C:\Users\Jonathan\Desktop\AsaCli-win-2.0.150\res\hostfxr.dll], HRESU
LT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Users\Jonathan\Desktop\AsaCli-win-2.0.1
50\res\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
~~~

not sure how to process.  Thank you.

**Comment by gfs** [comment]
If you flow the URL in the error message you'll see there are two KBs you need to install to resolve the hostfxr issue.
