### ISSUE TITLE
hostfxr.dll round #2

### ISSUE THREAD

**Issue by DigiAngel** [microsoft/AttackSurfaceAnalyzer#226]
So I was unable to reopen the original ticket, so here's another one:

~~~
Failed to load the dll from [C:\Users\Jonathan\Desktop\AsaCli-win-2.0.150\res\hostfxr.dll], HRESU
LT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Users\Jonathan\Desktop\AsaCli-win-2.0.1
50\res\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
~~~

I'd already followed the link and installed all the dependencies....hence my opening this ticket.  Any suggestions?

**Comment by gfs** [comment]
Sorry. I don't have any additional advice. The documentation calls out two KBs you have to install to resolve this error. In my experience I hit this issue and installing those two KBs resolved it.

**Comment by DigiAngel** [comment]
I see.
