### ISSUE TITLE
[Request] Automatically launch browser if running slim gui

### ISSUE THREAD

**Issue by sritejp** [microsoft/AttackSurfaceAnalyzer#236]
**Describe the bug**
GUI is not launching for 2.0.154 on Windows Server2012 or 2019

**To Reproduce**
1) Download AsaGUI-slim-windows-2.0.154.zip
2) Extract & run AttackSurfaceAnalyzer-GUI.exe
3) Hosting environment: Production
Content root path: C:\Users\sritpuvv\Downloads\AsaGui-slim-windows-2.0.154\AsaGui-slim-windows-2.0.154
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
4) App just running in the background

**Expected behavior**
Basic GUI should launch ASAP

**System Configuration (please complete the following information):**
 - OS: WINDOWS
 - OS Version: WINDOWS Server 2012R2 standard & WINDOWS Server 2019 standard
 - Application Version: v.2.0.154+303aa9fef5
 - CLI or GUI: GUI

**Comment by gfs** [comment]
You need to navigate your own browser to localhost:5000 to use the slim gui. We are working on having detection to auto launch a browser window when running outside the electron environment in 2.1.

**Comment by gfs** [comment]
Change now ported to 2.0.
