### ISSUE TITLE
[Request] Ability to delete results in GUI

### ISSUE THREAD

**Issue by rbsec** [microsoft/AttackSurfaceAnalyzer#242]
**Is your feature request related to a problem? Please describe.**
Unless I'm being very stupid, currently there does not appear to be any way to delete scan results in the application (beyond deleting the entire SQLite database, or manually going in to the database and removing them from there). The results also take up a significant amount of disk space (two static scans and few minutes of live monitoring resulted in a ~3GB database).

**Describe the solution you'd like**
It would be nice to be able to delete results directly from the web interface (and possibly have to have "Delete All" option which purges all of the results - although this can easily be done by just deleting the database).

**System Configuration (please complete the following information):**
* OS:  Windows
* OS Version: 10
* Application Version: Gui-slim-win10-2.0.154+303aa9fef5
* CLI or GUI: GUI-slim

**Comment by gfs** [comment]
Hey @rbsec,

We will look into adding this to the gui for 2.1. 

A workaround for now is to use the CLI which has ```config --delete-run```. The same database can be used with the CLI and GUI.

**Comment by rbsec** [comment]
@gfs,

Glad I wasn't just being stupid and missing something in the UI. I just ended up deleting the SQLite DB in the end (because I wanted to drop all the results), but good to know that there's a CLI option to be more specific.

Thanks

**Comment by gfs** [comment]
Depends on #316
