### ISSUE TITLE
Windows GPO Collection

### ISSUE THREAD

**Issue by guyacosta** [microsoft/AttackSurfaceAnalyzer#245]
**Is your feature request related to a problem? Please describe.**
Windows Group Policy Objects should be collected

**Describe the solution you'd like**
Windows Group Policy Objects should be collected

**System Configuration (please complete the following information):**
* OS: Windows
* OS Version:

**Comment by gfs** [comment]
It looks like we can do this with the registry collector. @guyacosta do you think an analyer rule is sufficient for this - we can flag changes to group policy objects in the [registry](https://www.rickyadams.com/wp/index.php/2016/04/23/windows-group-policy-history-stored-in-registry/) trivially and flag them as GPO changes.

COM Objects are treated similarly in the COMObject collector.  I'll do this for 2.3.
