### ISSUE TITLE
Attack Surface Analyzer doesn't run on Nanoserver

### ISSUE THREAD

**Issue by cmesyngier** [microsoft/AttackSurfaceAnalyzer#254]
**Describe the bug**
Running ASALaunch.bat on a Windows nanoserver 1809 (using the container version) does not 
trigger any collectors.

**To Reproduce**
1. Create a dotnet core 2.2 nanoserver container and start a command prompt using: 
```
docker run -it -u ContainerAdministrator mcr.microsoft.com/dotnet/core/sdk:2.2-nanoserver-1809 cmd
```
2. On the command prompt, execute the following to download ASA:
```
curl -o ./asa.zip -OL -G https://github.com/microsoft/AttackSurfaceAnalyzer/releases/download/v2.0.154%2B303aa9fef5/AsaCli-win-2.0.154.zip
```
3. Create a directory to unzip
```
mkdir app
cd app
```
4. Unzip
```
tar -xvf ../asa.zip
cd AsaCli-win-2.0.154
```
5. Run ASA
```
AsaLaunch.bat collect -all
```
6. Observe that nothing happens. Process terminates immediately

**Expected behavior**
ASA will start the collection process

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 1809
 - Application Version: -2.0.154
 - CLI or GUI: CLI

**Additional Context**

**Comment by cmesyngier** [comment]
Reopening after editing the docker run command to specify a dotnet core 2.2 base image

**Comment by gfs** [comment]
Are you having issues running the exe directly?  You don't need to use the script.

**Comment by cmesyngier** [comment]
I tried running the exe directly and the same happens, it terminates immediately

**Comment by gfs** [comment]
Thanks.  We did not test on nanoserver so I suspect as is it something basic isn't supported. I will keep this on the list to investigate.

**Comment by cmesyngier** [comment]
Sounds great, thanks Gabe!

**Comment by gfs** [comment]
This now works for me with the following steps. Note that User, Service and Firewall collectors don't work on Server Core, it appears the WMI mechanisms we're using aren't supported.  Also, I've identified a bug in the registry collector so it will also currently crash (once #299 is fixed you'll be able to run "Cclfpr" to collect the most amount of data, or alternately just use -a and have the incompatible collectors ignored).  

`docker run -it -u ContainerAdministrator mcr.microsoft.com/dotnet/core/sdk:3.0-nanoserver-1903 cmd`

```
curl -o ./asa.zip -OL -G https://github.com/microsoft/AttackSurfaceAnalyzer/releases/download/v2.1.28-beta%2B7e04a764f9/Asa-win-2.1.28-beta.zip
mkdir app
cd app
tar -xvf ../asa.zip
cd Asa-win-2.1.28-beta
AsaLaunch.bat collect -Cclfp
```
