### ISSUE TITLE
Link Attack Surface Analyzer from Microsoft SDL resource page

### ISSUE THREAD

**Issue by scovetta** [Microsoft/AttackSurfaceAnalyzer#27]
**Is your feature request related to a problem? Please describe.**
The [Microsoft SDL resource page](https://www.microsoft.com/en-us/securityengineering/sdl/resources) contains Attack Surface Analyzer (classic) as in the legacy/retired section.

**Describe the solution you'd like**
Move ASA from the Retired to the Tools section. Change the link to the GitHub project page, and add a link to get to the classic edition.

FYI @BruceCowper

**Comment by Guydalf** [comment]
In-progress

**Comment by Guydalf** [comment]
Done.  Change is live.
