### ISSUE TITLE
AsaLaunch.bat and AsaLaunchGui.bat are broken in latest 2.1 beta

### ISSUE THREAD

**Issue by scovetta** [microsoft/AttackSurfaceAnalyzer#287]
**Describe the bug**
The batch files are looking for Asa.exe in .\res, but it's actually in .\res\Asa. Probably makes more sense to put all of the files directly in res rather than changing the batch file.

Found in this one:
https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.1.5-beta%2Bf4e83c478a

**Comment by gfs** [comment]
This has been fixed in the code but it looks like the pipeline has been failing.  Investigating that.
