### ISSUE TITLE
Latest GUI: 404s to static resources

### ISSUE THREAD

**Issue by scovetta** [microsoft/AttackSurfaceAnalyzer#288]
**Describe the bug**
When I run the latest ASA 2.1 beta GUI, all of the JS/CSS/png files come back as 404s.

**Additional Context**
The page also doesn't work, but that isn't surprising since the JS fails to load.

**Comment by gfs** [comment]
This appears to have to do with the Launch script.  Launching it directly seems to work.

**Comment by gfs** [comment]
Fixed.
