### ISSUE TITLE
MacOS res/Asa: command not found

### ISSUE THREAD

**Issue by exquirentibus** [microsoft/AttackSurfaceAnalyzer#289]
I decompressed Asa-macos-2.1.12-beta into a folder on my desktop and open terminal set to that location

I enter ls and can see the two shell scripts:
AsaLaunch.sh and AsaLaunchGui.sh 

and the res directory.

I type in sh ./AsaLaunch.sh and enter my password for sudo from the .sh script.

It displays:

sudo: res/Asa: command not found

I can see that the Asa executable has execute permissions for me.

1. What obvious mistake am I making?  Maybe the folder should be located somewhere else or needs to have some permission set or a path set somewhere?

2. For using the command line version, are there any example scripts where the drive to be scanned is specified?  I can specify Windows drives, but am unfamiliar with MacOS usage.

I can see the volumes using cd /volumes, then ls - but ... possibly there is some tricky syntax to specify the volume that is second nature to someone familiar with unix?

3. Besides monitoring before and after a program's installation, my intended purpose is to scan my boot drive and then scan a Carbon Copy of the boot drive and compare them. 

I'm trying to account for 100GB of missing data on the Carbon Copy drive, and want to insure it's just temp files (from Logic Pro Sound Library Manager installs - or something I don't need.

Thanks!

**Comment by scovetta** [comment]
Similar to #287.

**Comment by gfs** [comment]
Hey @exqiorentibus,

Thank you for your report.

1. I'll investigate this.  For now, please try running ```Asa``` directly without the script and let me know if that works for you.

2. The Mac OS File system is rooted at ```/``` with specific volumes at "/Volumes" you would just specify the directory in ```/Volumes``` you were interested in. For example: ```sudo asa collect -f -directories "/Volumes/Location"``` Alternately you can just run ```sudo asa collect -f``` to gather everything in ```/```

3. Note that ASA uses the absolute path as the "Identity" of a collected file object.  So if your "Carbon Copy" drive isn't located at the same place it won't detect that those are the same files.

For example, there is currently no capability to compare: ```/Volumes/Directory1``` to ```/Volumes/Directory2```, it would detect that those are two entirely separate folders..

**Comment by exquirentibus** [comment]
While in the folder with asa, I tried using terminal:

sudo asa gui
and got:
asa: gui: no such file or directory

Also tried sudo asa --version and help, etc. - with the same result

When I double clicked on the asa executable, it gives me a terminal window that shows:

Asa 2.1.12-beta+141cb8dc4b and a copyright
....
no verb selected

So, it does seem to have all the components and it does run.   

I'm no doubt making some stupid beginner mistake in syntax.   For neophytes, some basic MacOS script examples might be useful?

--
As to #3, if I boot from the Carbon Copy backup, will the absolute path the be same, or will there be an issue with the volume name being different?  I can't really remove or disable the main boot volume as it's an NVMe seated on the motherboard (Gigabyte lets me disable a SATA but not the NVMe for some reason?).

I just can't figure out where the missing files are using the tools that I have -the SSD seems identical when using Path Finder's Size Browser and the 'Volume Disk Usage Details' utility from Bombich (Carbon Copy's developer),  But the 'info' button in Disk Utility shows 100GB less  free space on the copy and about 900 less files. I'm perplexed?

It's not useful to compare a before and after of the same drive in this case as the 'before' is on the main drive and the 'after' is the Carbon Copy (in theory) identical backup of the main drive.

Maybe an 'optional override' option could be added so that different volumes could be compared?

I can think of situations on Windows where I'd also like to compare files on different volumes, like when moving a large data volume with 1000's of files using Acronis to a new SSD on a different computer - nice to know everything actually made it intact.

**Comment by gfs** [comment]
Try running the executable you clicked on directly in the terminal (in your package is should be located at res/Asa/Asa).  The current package has a bug where there is an extra folder so instead of res/Asa being the binary it is a folder so following the script isn't correct.

So from the directory containing AsaLaunch.sh, ```sudo res/Asa/Asa collect``` should work.
-------
My understanding of how CCC works it will be identical if you boot off of it.  However, I think ASA isn't the right tool to solve your problem here.  Try using rsync: ```rsync -avnc $SOURCE $TARGET``` https://unix.stackexchange.com/questions/57305/rsync-compare-directories

On Windows you can accomplish the same thing using rsync (perhaps through cygwin) or using Robocopy.  https://improvingsoftware.com/2013/09/09/how-to-diff-two-folders-from-a-windows-command-prompt/

We don't have any plans to add this to ASA.

**Comment by exquirentibus** [comment]
Thanks for your help and the great work on this tool!!!
