### ISSUE TITLE
registry change not detected

### ISSUE THREAD

**Issue by rzcrjz** [microsoft/AttackSurfaceAnalyzer#301]
using Asa-win-2.1.29-beta on Windows 10 1809.
running base run , finished with no errors
created registry key on the machine to test, in HKLM hive (currentversion\run)
run second run, finish with no errors

result => no changed detected  (%error.nodifference) 
expected result => registry key addition detected.

**Comment by gfs** [comment]
Thank you for the report.  I'll investigate if there was a regression.

**Comment by gfs** [comment]
I think you were experiencing a GUI bug.  I've confirmed the registry collector is working.

**Comment by rzcrjz** [comment]
I retried this on a windows 10 system with Asa-win-2.1.43
I ran asa collect -r
I manually added a key and a string to the registry (hklm) , uner hklm/..currentversion/run (which is a key I would always like to check on as a software packager/deployer.)
I reran asa collect -r 
The I ran asa export-collect

while the resulting json had a lot of data , the registry key I changed to test, was not included in the output.

**Comment by XYujie** [comment]
I am getting this problem now, how did you fix that? 
This is the command I am using: `collect --registry --hives LocalMachine`
P.S. I am running  ASA 2.3.297 on Windows Server 2022.
