### ISSUE TITLE
Compare run status doesn't properly update for fast collectors.

### ISSUE THREAD

**Issue by Guydalf** [microsoft/AttackSurfaceAnalyzer#304]
**Describe the bug**
The status is not shown for the results analyze being completed.  Only examination of the filtering options provides a clue that they are ready.  Used to display a message...

**To Reproduce**
Run two scans
Run a comparison

**Expected behavior**
Provide a message of success or failure.

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI: GUI

**Additional Context**

**Comment by Guydalf** [comment]
![asabug](https://user-images.githubusercontent.com/47648296/67438409-3c826480-f5a8-11e9-9cd0-cca9da11278f.png)

**Comment by gfs** [comment]
This appears to be an edge specific bug.  For now, please use Firefox or Chrome.  I'll put this on the backlog to investigate.

**Comment by gfs** [comment]
Was finally able to reproduce something similar in Firefox. Not sure why its happening yet though.
