### ISSUE TITLE
GUI Does not show service changes

### ISSUE THREAD

**Issue by Guydalf** [microsoft/AttackSurfaceAnalyzer#305]
**Describe the bug**
Tool at least is not detecting service changes.

**To Reproduce**
Run ASA 2.1.30-Beta and scan for just services
Run the command to add a service i.e. sc create asademo99 binpath=c:\temp\asademo.exe
Run ASA again for a second snapshot
Run the results and filter for services

**Expected behavior**
Should detect the service added

**Screenshots**
see screenshot

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.1.30-BETA
![asabug2](https://user-images.githubusercontent.com/47648296/67438748-2cb75000-f5a9-11e9-82de-cb46d336f323.png)

 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment]
Please be clear about what interface you're referring to.  This is a GUI bug, not a data collection bug.  You can test the data collection itself in the commandline interface.

**Comment by Guydalf** [comment]
Note the GUI reference in the bug details.
