### ISSUE TITLE
ASA GUI Page Not Found on Initial Load in Edge Requiring Refresh

### ISSUE THREAD

**Issue by Guydalf** [microsoft/AttackSurfaceAnalyzer#308]
**Describe the bug**
When launching asalaunchgui the UI does not always appear at first requiring a refresh or two of the page to load.

**To Reproduce**
open an admin cmd prompt
run asalaunchgui on a Windows system with Edge

**Expected behavior**
Page loads on first attempt

**Screenshots**
![asaguipageloaderr](https://user-images.githubusercontent.com/47648296/67514352-752a4880-f651-11e9-8cbe-e9308be79ce8.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.1.30-beta
 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment]
Is this Edge only?

-------- Original Message --------

**Comment by gfs** [comment]
I already wait a full second before launching the browser, I'm not sure how long I should realistically make the timeout. This might just happen on machines that are too slow?

`((Action)(async () =>
            {
                await Task.Run(() => SleepAndOpenBrowser(1000)).ConfigureAwait(false);
            }))();`
