### ISSUE TITLE
viewing 'list of changes' on GitHub 'release page', requires authentication for https://spsprodeus27.vssps.visualstudio.com/_signedin

### ISSUE THREAD

**Issue by mi-hol** [microsoft/AttackSurfaceAnalyzer#311]
**Describe the bug**
 'list of changes' should be public information but is requiring authorization

**To Reproduce**
1. Go to https://github.com/microsoft/AttackSurfaceAnalyzer/releases
2. Click on 'This list of changes was auto generated.'
3.  get error 401

**Expected behavior**
the 'list of changes' should 
**Screenshots**
![image](https://user-images.githubusercontent.com/22799428/68376550-0d8ff500-0149-11ea-860c-c88f54562d77.png)

![image](https://user-images.githubusercontent.com/22799428/68376648-36b08580-0149-11ea-9cdf-541666389fcf.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 1803

**Comment by gfs** [comment]
The auto generated list of changes itself is listed in full there, the link only provides debugging information for the build itself.  That information is not available publicly.
