### ISSUE TITLE
Asa.exe export-collect --analyze does not update the "findings" table

### ISSUE THREAD

**Issue by tfosm** [microsoft/AttackSurfaceAnalyzer#323]
**Describe the bug**
If you perform "Run analysis" in the GUI, the "findings" table in the sqlite database gets updated (I assume this is the table holding all severe findings and that the higher value in the "level" column, the more severe issue)

**To Reproduce**
1. Create a baseline: Asa.exe collect --runid BASELINE -c -p -s -r -u -F -C -l
2. Install some software
3. Run a new scan: Asa.exe collect --runid EW_INSTALLED -c -p -s -r -u -F -C -l
4. Analyze the result between the two scans: Asa.exe export-collect --firstrunid BASELINE --secondrunid EW_INSTALLED --analyze

**Expected behavior**
I would expect that the "findings" table gets updated but it hold zero rows. If the GUI command "Run analysis" does something that you can't do on the command line, this is a bug. Otherwise, please document the command line options it corresponds to.

**Screenshots**

**System Configuration (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.1.1.41]
 - CLI or GUI: CLI

**Additional Context**
The CLI tool as well as the database structure is poorly described.

**Comment by gfs** [comment]
This is not a bug, this is by design.  The export-collect command exports a json report and does not update the database.

The findings section of the database needs to be populated in order for the Gui result paging to function.

I can take this as a feature request for 2.2.

**Comment by tfosm** [comment]
Ok, thank you for this. So there is no way to update this table the CLI? Our company wants to fully script this. 

Is there a database decsription available? Is my understranding correct the "findings" table holds all severe findings and that the higher value in the "level" column, the more severe issue?

**Comment by gfs** [comment]
I actually already have this mostly implemented. I'll have an update of 2.1 available today with a "SaveToDatabase" option.

> Is there a database decsription available? Is my understranding correct the "findings" table holds all severe findings and that the higher value in the "level" column, the more severe issue?

Correct.
