### ISSUE TITLE
registry key addition not detected 

### ISSUE THREAD

**Issue by rzcrjz** [microsoft/AttackSurfaceAnalyzer#329]
I retried this on a windows 10 system with Asa-win-2.1.43
I ran asa collect -r
I manually added a key and a string to the registry (hklm) , uner hklm/..currentversion/run (which is a key I would always like to check on as a software packager/deployer.)
I reran asa collect -r
The I ran asa export-collect

while the resulting json had a lot of data , the registry key I changed to test, was not included in the json output.

**Comment by gfs** [comment]
Thank you for your report and explanation of your use case.

I'll take a look and see if I can reproduce.

-------- Original Message --------

**Comment by rzcrjz** [comment]
I think I overlooked the obvious, it's excluded in the filters.json : "^HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion"

I'll try to edit this and then I think it should work.

What would be the reasoning to exclude such an impactful key (i.e. 'RUN' which would be imho an important attack vector, from this capture?, was it generating too much noise?

**Comment by gfs** [comment]
That key was generating a lot of noise. You raise a good point for the use case for why this key shouldn't be excluded. We are working on improvements for the default filters so this is great feedback.

-------- Original Message --------

**Comment by rzcrjz** [comment]
I reran asa collect with --no-filters and the created key is still not in the output, should I use another (or additional) method to include it? I can't find the filters.json file in the .zip I'm using, shall it be created (in which path?)

**Comment by gfs** [comment]
You can get filters.json here: https://github.com/microsoft/AttackSurfaceAnalyzer/blob/master/filters.json

However, no-filters should have worked as well. Hmm.

-------- Original Message --------

**Comment by rzcrjz** [comment]
it does not seem to be related to the filters indeed. I created a key directly under HKLM/software and it wasn't picked up  either in the output. Same run I added a key under HKCU/software and this was in the json comparison.
can't explain this behavior, but I can consistently replicate it.

**Comment by gfs** [comment]
Thanks.  I'll investigate further.

**Comment by rzcrjz** [comment]
I did some more testing on different Windows 10 endpoints
I can't consistently reproduce this behaviour on all clients either, some of my Windows 10 clients this seems to work perfectly, but on others this seems to fail.
for me to be able to useful, I need to be able to rely on this in all cases as I would like to use this during app pentesting/ applocker policy compliance testing on a 'clean' virtual machine with snapshots. Is it possible to enable more logging to see why that key is not captured? there is no error output when this happens.

**Comment by gfs** [comment]
Thanks for performing the extra validation.

Definitely understand this is frustrating. We want ASA to be reliable enough for your use case.

You can try adding the --verbose flag. But I don't expect it will add something meaningful for this case.

I'm investigating more but I dont have an ETA yet on when a fix will be available.

-------- Original Message --------

**Comment by gfs** [comment]
You can also try --debug, which should print errors if it has trouble processing a registry key.

**Comment by gfs** [comment]
I believe this will be fixed in the newest 2.1 (the build is running now and should be available in about 30 min - 1 hr from this post).  Reopen if you're still having issues.
