### ISSUE TITLE
FileSystemCollector stalls on Mac OS

### ISSUE THREAD

**Issue by gfs** [microsoft/AttackSurfaceAnalyzer#331]

**Comment by yitam** [comment]
Thanks @gfs I will wait till this is fixed.

**Comment by gfs** [comment]
@yitam You should be good to go.

**Comment by yitam** [comment]
Thanks @gfs I will check that later, but the stalling problem in ubuntu 18.04 (shown in #328 ) still exists.

**Comment by gfs** [comment]
@yitam Investigating.

**Comment by gfs** [comment]
@yitam I believe this is now fixed for good on both platforms.

**Comment by yitam** [comment]
> I believe this is now fixed for good on both platforms.

Unfortunately, @gfs, this is not the case...  in a clean Ubuntu 18.04 I now see different errors. On Mojave, it's hung. Should I create two new issues?

**Comment by gfs** [comment]
Yes.

-------- Original Message --------
