### ISSUE TITLE
Gui fails to work if run from external directory

### ISSUE THREAD

**Issue by skottmckay** [microsoft/AttackSurfaceAnalyzer#349]
It would be helpful to explicitly state that you must run asa.exe from the current directory, or for it to detect that this isn't the case and either fix the situation or provide an error message. 

I naively ran it like this:
C:\temp> C:\Users\User\Downloads\Asa-win-2.1.62\Asa-win-2.1.62\asa\Asa.exe gui 

The server runs and you can navigate to a page to seemingly start a scan, but clicking on the Collect Data button does nothing. In hindsight it's a very basic page and the broken image was a hint, but for a first time user it's not obvious that something is badly wrong with how it's being run.

**Comment by gfs** [comment]
Thanks for the report Scott.

Sorry you're having trouble.

I don't believe you should have to run it from a specific directory. I'll run some more tests to check for regressions.

**Comment by gfs** [comment]
Thanks, I've reproduced this now.  This appears to be the default behavior of .NET.  Investigating how to modify that.
