### ISSUE TITLE
Javascript errors on Win GUI launch

### ISSUE THREAD

**Issue by HoHo2020** [microsoft/AttackSurfaceAnalyzer#350]
**Describe the bug**
The 2.0.163 build when launching the GUI throws up a JavaScript error. See screenshot.
The app starts, but with display errors.

**To Reproduce**
1. Go to Attack Surface Analyzer.exe 
2. Click on Attack Surface Analyzer.exe using Admin role
3. See error

**Screenshots**

<img width="792" alt="200129_ASA_VScript_Error" src="https://user-images.githubusercontent.com/60465883/73443045-3abdff00-4356-11ea-8ac2-55f1c690062e.PNG">

<img width="903" alt="200129_ASA_VScript_Error_2" src="https://user-images.githubusercontent.com/60465883/73443053-3f82b300-4356-11ea-8b71-1027e2e05a3e.PNG">

**System Configuration (please complete the following information):**
 - OS Version: Windows 10 [1903]
 - Application Version: AsaGui-win10-2.0.163.177bac6213
 - CLI or GUI: GUI

Download: https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.0.163%2B177bac6213

**Additional Context**
WinGUI for 2.1 available?

**Comment by gfs** [comment]
Thanks for your report.

We deprecated the full electron version with 2.1 but you can still get the GUI interface on 2.1 by running “Asa.exe GUI” on 2.1 from an administrative command prompt or power shell.

**Comment by HoHo2020** [comment]
It worsk with Asa-win-2.1.62.zip (CMD: ...\Asa.exe gui) ;-)
