### ISSUE TITLE
Fail to commit data

### ISSUE THREAD

**Issue by PCPanos** [microsoft/AttackSurfaceAnalyzer#368]
Environment:
Clean windows 10 install running as a VM Workstation Pro Image. Running from c:\users\MyUser>
Attack Surface Analyzer 2.2 - Alpha
Have also tried running straight from C:\, no difference

Every time I run asa collect it creates the asa.sqlite files but fails to commit data to the files:

>Failed to commit data to asa.sqlite_9,    at AttackSurfaceAnalyzer.Objects.SqlConnectionHolder.Commit() in C:\Program Files\AttackSurfaceAnalyzer-master\Lib\Objects\SqlConnectionHolder.cs:line 86
System.NullReferenceException: Object reference not set to an instance of an object.
   at AttackSurfaceAnalyzer.Objects.SqlConnectionHolder.Commit() in C:\Program Files\AttackSurfaceAnalyzer-master\Lib\Objects\SqlConnectionHolder.cs:line 86

I'm unsure if this is related, but i also cannot export-collect after running 2:

>asa export-collect
[14:53:53 INF] AttackSurfaceAnalyzer v.2.2.0-alpha
[14:53:54 FTL] Couldn't determine latest two run ids. Can't continue.

**Comment by gfs** [comment]
I have a major patch coming that will affect the alpha soon and should resolve this issue.  See #367.

For production use I recommend using the official releases of 2.1 for now.

**Comment by gfs** [comment]
@PCPanos I can't replicate this on either the latest master or the latest release.  Please try the latest release here (https://github.com/microsoft/AttackSurfaceAnalyzer/releases) and open a new issue if you're still having trouble.
