### ISSUE TITLE
FileSystemCollector is Stalling

### ISSUE THREAD

**Issue by gfs** [microsoft/AttackSurfaceAnalyzer#417]
Experiencing this on both Windows and Mac.

**Comment by reidmefirst** [comment]
Any idea what versions are impacted? Been waiting a while on a run using release 2.1.80 (let it run for a bit over an hour, on a freshly installed VM). Not sure if this is normal or if the stable 2.1 release builds are also impacted by this stall?

**Comment by gfs** [comment]
This should be a 2.2 only issue.

Are you seeing ASA have a near 0% CPU utilization while it appears to be stalled?

You can also add --verbose to see every filename as it's parsed. If you're seeing this bug that output will freeze.

Let me know if you're still having issues.

-------- Original Message --------

**Comment by gfs** [comment]
Just saw you mentioned it's been running for an hour. That shouldn't be the case on a fresh VM. If you could run it with verbose to nail down the directory it's stalling on that may help me.

**Comment by reidmefirst** [comment]
Yeah I noticed with 2.2 it was using 0% CPU. 2.1 it is using some cpu time. Anyway, ASA is not at fault here. I think I get to blame the windows 10 update team =). I updated the VM the other day, and didn't notice that it left me with a > 30GB C:\Windows.old. As an added bonus, even local administrator has no access to the files here (so, ASA is giving a lot of file permission errors trying to read these files, I guess it wants to record a hash of each file? Lots of 'Couldn't chomp 4 bytes of <filename> (System.UnauthorizedAccessException)' and inability find group from SID errors).

**Comment by reidmefirst** [comment]
(I should note that in between troubleshooting I had attempted to run 2.1 without the filesystemcollector, and it resulted in spending forever collecting registry key data....I suspect that I'll find a similar monstrosity from the recent windows os update involving registry keys. Sad that ASA doesn't spit out what registry keys it is inspecting with the --verbose flag though, will have to watch it with procmon I guess. A feature request might be to honor --verbose option under '-r' and even 'gui' options ;-)).

**Comment by gfs** [comment]
Thanks for the extra context.

We try to chomp 4 bytes off every file to check if it's an executable. And then we check if it's signed if it's a windows binary. There's currently no setting to disable that. If you'd like one please file an issue.

The can't map Sid errors can be safely ignored that's just trying to turn windows permissions into human readvle strings.

I believe verbose in gui is included in 2.2.

If you could open an issue for registry collector and I'll definitely handle it soon.

-------- Original Message --------

On May 5, 2020, 11:16 AM, Reid Wightman < notifications@github.com> wrote:

(I should note that in between troubleshooting I had attempted to run 2.1 without the filesystemcollector, and it resulted in spending forever collecting registry key data....I suspect that I'll find a similar monstrosity from the recent windows os update involving registry keys. Sad that ASA doesn't spit out what registry keys it is inspecting with the --verbose flag though, will have to watch it with procmon I guess. A feature request might be to honor --verbose option under '-r' and even 'gui' options ;-)).

—

You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/microsoft/AttackSurfaceAnalyzer/issues/417#issuecomment-624222209">https://github.com/microsoft/AttackSurfaceAnalyzer/issues/417#issuecomment-624222209", "url": "[https://github.com](<a href=)/microsoft/AttackSurfaceAnalyzer/issues/417#issuecomment-624222209">https://github.com/microsoft/AttackSurfaceAnalyzer/issues/417#issuecomment-624222209", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by gfs** [comment]
On 2.2 this is being caused by a hang in X509Certificate2.Import. https://github.com/dotnet/core/issues/4649

I'm disabling our functionality that uses it in both 2.1 and 2.2 in new releases later today until that bug is addressed.

-------- Original Message --------

**Comment by gfs** [comment]
One cause of stalls should be fixed in #418

**Comment by gfs** [comment]
Try out [2.1.83](https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.1.83%2Bd5436e7869) or [2.2.19](https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.2.19-beta%2Bfde9ee0611).

**Comment by gfs** [comment]
@reidmefirst #419 is done and adds verbose tracing to registry collector on 2.2 and 2.1. Builds are in the pipeline now. Should be ~2.1.84 and ~2.2.21 will have Fixes for this bug, Verbose on Registry and Verbose on GUI.

**Comment by gfs** [comment]
@reidmefirst Have reproduced a registry collector stall #424 

For reproducing issues on the newest builds use `--verbose --singlethread` it will run slower (no parallelization) but it runs the same algorithm, and the log output makes more sense.
