### ISSUE TITLE
RegistryCollector Out of Memory Exception

### ISSUE THREAD

**Issue by a-gazin** [microsoft/AttackSurfaceAnalyzer#439]
**Describe the bug**
Out of memory exception hit.
Error: 
Error collecting from RegistryCollector: Exception of type 'System.OutOfMemoryException' was thrown. at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.RunCollectCommand(CollectCommandOptions opts) in D: ...\Cli\Program.cs:line 1050

**To Reproduce**
1. Run the command line:  `Asa.exe collect -r`
2. Will need to wait some time (can take up to 40 minutes+)
3. System.OutOfMemoryException is thrown

**Expected behavior**
To not throw an error.

**Screenshots**
![Crash](https://user-images.githubusercontent.com/61299470/81974393-62ba3100-95da-11ea-9f8c-b9f3962eca0f.png)

**System Configuration:**
 - OS: Windows
 - OS Version: Windows 10 Version	10.0.18362 Build 18362
 - Application Version: 2.2.32+9f00933482
 - CLI or GUI: CLI (run as administrator)
 - RAM: 4GB

**Additional Context**
There may be a problem with actually going through the hives.
specifically specifying `--hives ClassesRoot` or `--hives LocalMachine`

**Comment by a-gazin** [comment]
@gfs

**Comment by gfs** [comment]
Thanks for your report. 

I'm interested in the long run time here as well. Is this a lower powered device? How many logical/physical cores does it have?

A comment on the command you are running. 
 `--gatherverboselogs` is for the Log collector, it doesn't affect application logging level. 
`--verbose` overwrites `--debug`
If you are using `--verbose` I recommend you use `--singlethread` as well to help the output be a little more comprehensible.

Interestingly, I don't see any verbose output in your console above either.  Can you try running `asa collect -r --singlethread --verbose` and seeing if you see the verbose output?  I can't reproduce the lack of logging output.

The stack trace here unfortunately is a little short, but I'll investigate further. It may result in having a `--lowmemoryusage` option which will somewhat impair performance in return for lower memory usage.

**Comment by gfs** [comment]
I just tested and have no trouble specifying hives. I'm running 2.2.33.

`asa collect -r --debug --verbose --hives CurrentUser\Accessibility,ClassesRoot`

**Comment by gfs** [comment]
I'm pushing an update to 2.2 that has an *experimental* `--lowmemoryusage` option. It should be 2.2.35 and available shortly.

`asa collect -r --lowmemoryusage`

or with verbose

`asa collect -r --singlethread --verbose --lowmemoryusage`

If this system is IO Constrained you may want `--shards 1`

Low Memory Usage mode applies to the File, Registry and Event Collectors and restricts how large the in memory cache of collected objects can become and for all collectors how large the database write cache can become.  The CLI continually pulls the results out of the collectors and writes them out to the database cache, and a separate thread writes from that cache.

This new mode adds checks before writing to either the Results in those collectors or the database Write Cache and waits until the cache falls below a max size before allowing the write and continuation of the collector.

I've set that size at 1000 elements, which should be pretty conservative.

**Comment by a-gazin** [comment]
Thank you for the quick response and finding a solution quickly!
