### ISSUE TITLE
Registry Collector getting stuck

### ISSUE THREAD

**Issue by a-gazin** [microsoft/AttackSurfaceAnalyzer#441]
**Describe the bug**
When running the registry collector, It seems that the there is an infinite loop for certain subkeys 

**To Reproduce**
1. Run Command: `Asa.exe collect -r --hives LocalMachine--verbose`   (specifically SAM)
2. Observe that the collector continually parses/finish parsing LocalMachine\SAM.

**Expected behavior**
To not get stuck in the subkey.

**Screenshots**
![Capture_Cmd](https://user-images.githubusercontent.com/61299470/82075246-cc951200-9690-11ea-9f49-33b2006c1644.PNG)
![Capture_SAM](https://user-images.githubusercontent.com/61299470/82075262-d28af300-9690-11ea-8552-1e06e61e9330.PNG)

**System Configuration:**
 - OS: Windows
 - OS Version: Windows 10 Version 10.0.18362 Build 18362
 - Application Version: 2.2.35+2e84f385ff
 - CLI or GUI: CLI (run as admin)

**Additional Context**
 - May be to do with the a key containing a subkey with the same name?

**Comment by a-gazin** [comment]
@gfs 
Sorry i don't mean to always @ you but it seems this is not getting assigned to anyone after creation.

**Comment by gfs** [comment]
Thanks for your report.  I can investigate this afternoon.

@me is fine, but I get notifications for each new issue automatically.  We don't have the project automatically assign issues to anyone, I triage them as they are created.

**Comment by gfs** [comment]
Try 2.2.36.

**Comment by a-gazin** [comment]
Yes this change fixes the issue. Thanks!!
