### ISSUE TITLE
FileSystem Collector Stalling

### ISSUE THREAD

**Issue by a-gazin** [microsoft/AttackSurfaceAnalyzer#445]
**Describe the bug**
When running the file system collector on a Windows 10 machine, under 2 conditions the program does not go through the file systems. 
1. Not specifying the directories.
2,. Specifying the `--directories C:\`

**To Reproduce**
1. Run the command: `Asa.exe collect -f`
2. Programs does not cycle through directories.

**Expected behavior**
To run through all the file systems (when not specified) 
and when specifying `C:` to go through the C drive.

**Screenshots**
Not Specifying directories:
![Capture_File1](https://user-images.githubusercontent.com/61299470/82171701-00348f80-987d-11ea-831b-a05012ccc113.PNG)

Specifying C:\
![Capture_File2](https://user-images.githubusercontent.com/61299470/82171704-00cd2600-987d-11ea-8360-2108c0e25453.PNG)

Specifying C:\Windows
![Capture_File3](https://user-images.githubusercontent.com/61299470/82171705-0165bc80-987d-11ea-994c-91dd2e7aa3d8.PNG)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 10.0.18363 Build 18363
 - Application Version: v.2.2.36+fdd85d0d65
 - CLI or GUI: CLI

**Additional Context**

**Comment by gfs** [comment]
Fixed version building now. Check for new releases in the next hour. Thanks for your report!

-------- Original Message --------

**Comment by a-gazin** [comment]
Thanks!!
