### ISSUE TITLE
ServiceCollector stalling on Windows 8

### ISSUE THREAD

**Issue by a-gazin** [microsoft/AttackSurfaceAnalyzer#453]
**Describe the bug**
Service Collector is stalling on Windows 8.

**To Reproduce**
1. Run: `Asa,exe  collect -s --verbose`
2. Observe the stall

**Expected behavior**
Service Collector not stalling.

**Screenshots**
![Capture_Service](https://user-images.githubusercontent.com/61299470/82509107-d026ff80-9abb-11ea-9634-f994d0240794.PNG)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 8.1 64-bit
 - Application Version: v2.2.39+fee5e7655f
 - CLI or GUI: CLI

**Additional Context**

**Comment by gfs** [comment]
Thanks for your report. Investigating now.

**Comment by bazizi** [comment]
Just FYI,
I could reproduce the same issue on Windows Server 2012 R2.

![image](https://user-images.githubusercontent.com/7786414/82594883-9c9ab280-9b59-11ea-9b9d-aa701beab7d7.png)

**Comment by gfs** [comment]
I suspect this is related to a change I recently made in filesystem collector. Hoping to have a fix today.

**Comment by gfs** [comment]
Cannot reproduce this on Windows 10.
![image](https://user-images.githubusercontent.com/98900/82596488-3b281300-9b5c-11ea-94d0-741e39a42f6b.png)

**Comment by gfs** [comment]
Try 2.2.40.

**Comment by a-gazin** [comment]
Thanks! ASA is no longer stalling. 

There are still errors regarding: (Windows Server 2012, Windows 8)
Not: (Windows 10)

Would you like me to open a new issue or append this?

**Comment by gfs** [comment]
Please open a new issue. Thanks!
