### ISSUE TITLE
Fix documentation or change app behavior

### ISSUE THREAD

**Issue by jacobmsft** [microsoft/AttackSurfaceAnalyzer#454]
Documentation says:
To start a default all collectors run: asa collect

Actual behavior:
E:\t...Cli>Asa.exe collect
[20:44:31 INF] AttackSurfaceAnalyzer v.2.2.39+fee5e7655f
[20:44:34 WRN] No collectors have been defined.

**Comment by gfs** [comment]
Thanks. Should be `asa collect -a`

Sent from ProtonMail mobile

-------- Original Message --------
