### ISSUE TITLE
Component Governance Artifacts are being published to GitHub releases

### ISSUE THREAD

**Issue by gfs** [microsoft/AttackSurfaceAnalyzer#458]
See https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.2.40%2B0f97498320

A number of files generated by Component Governance are being published accidentally.

**Comment by gfs** [comment]
Also: Codesign summaries are being published inside of the Windows zip

**Comment by gfs** [comment]
Also: Platform zips are structure a bit confusingly.

Currently: `asa-win-2.2.40\windows\cli\Asa.exe`
Proposed: `asa-win-2.2.40\Asa.exe`

**Comment by scovetta** [comment]
> Currently: `asa-win-2.2.40\windows\cli\Asa.exe`
> Proposed: `asa-win-2.2.40\Asa.exe`

Yep, I like that. Maybe just `asa.exe` (lowercase)?
