### ISSUE TITLE
CodeQL is opening issues for files in docs/

### ISSUE THREAD

**Issue by gfs** [microsoft/AttackSurfaceAnalyzer#462]
The autogenerated docs have some issues identified in CodeQL which are not directly under our control. We shouldn't scan them.

**Comment by gfs** [comment]
@daalcant bump

**Comment by daalcant** [comment]
Unfortunately this is only supported for interpreted languages:
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#specifying-directories-to-scan
