### ISSUE TITLE
FileCollector not respecting directories options

### ISSUE THREAD

**Issue by a-gazin** [microsoft/AttackSurfaceAnalyzer#465]
**Describe the bug**
When specifying multiple directories for the file system collector, Only the first directory has results. This only occurs on Windows 8, Windows Server 2012, Windows Server 2012R2.
Does not occur on Windows 10, Windows Server 2016, Windows Server 2019.

**To Reproduce**
1. Run `asa.exe -f --verbose --directories "C:\Program Files","C:\Windows\System32"`
Note: you can use different directories and also add more if you want
2. Observe that the file system collector parses the first directory and does not go to the next specified directory.
3. File Collector completes

**Expected behavior**
To parse all directories given.

**Screenshots**
![Capture_File1](https://user-images.githubusercontent.com/61299470/83065866-09f68980-a019-11ea-87a7-b436125ff80a.PNG)
![Capture_File2](https://user-images.githubusercontent.com/61299470/83065656-b5530e80-a018-11ea-8b33-7b3dd598042b.PNG)

**System Configuration:**
 - OS: Windows
 - OS Version: Windows 8, Windows Server 2012, Windows Server 2012R2
 - Application Version: v2.2.41+4cdefe4f55
 - CLI or GUI: CLI

**Additional Context**

**Comment by gfs** [comment]
Thanks for your report. I'll investigate today.

**Comment by gfs** [comment]
I'm having more fundamental issues on my W8 VM - Collector running just being skipped entirely.

Not clear yet how long a fix will take.

**Comment by gfs** [comment]
I can now reliably reproduce this and it is bizarre.  I don't see anything platform specific in the code.  As you can see from the output it never gets to line 150 the second time to print out that it has started parsing the second root.

The code that splits directories is here:

https://github.com/microsoft/AttackSurfaceAnalyzer/blob/8445ac0dfbd1a3a481bc5fe4db1eeb18032a9a0a/Lib/Collectors/FileSystemCollector.cs#L46-L52

And the code that iterates over the provided directories is here:

https://github.com/microsoft/AttackSurfaceAnalyzer/blob/8445ac0dfbd1a3a481bc5fe4db1eeb18032a9a0a/Lib/Collectors/FileSystemCollector.cs#L148-L175

**Comment by gfs** [comment]
This wasn't fixed by #472 like I'd hoped.

**Comment by gfs** [comment]
There appears to be a bug in our command line parsing library on Windows 8 where anything after the first comma in an argument is getting swallowed so we don't even get to see it to split.

I fixed this by changing the delimiter to `^`.

For an example using your command above:
`asa collect -f --directories "C:\Program Files","C:\Windows\System32"`
becomes:
`asa collect -f --directories "C:\Program Files"^"C:\Windows\System32"`

**Comment by a-gazin** [comment]
Thanks!!!

**Comment by gfs** [comment]
I opened an issue with the maintainer of the library we use as well.

https://github.com/commandlineparser/commandline/issues/640

**Comment by a-gazin** [comment]
Actually this may have been due to user error and I apologize. I have been using powershell to run ASA. From what i have observed, comparing powershell to command prompt (before your changes v2.2.41).

Powershell
`Asa.exe collect -f --directories "C:\Program Files (x86)","C:\Program Files"`:      only the first works
`Asa.exe collect -f --directories "C:\Program Files (x86),C:\Program Files"`:         both work

Command Prompt:
`Asa.exe collect -f --directories "C:\Program Files (x86)","C:\Program Files"`:      both work
`Asa.exe collect -f --directories "C:\Program Files (x86),C:\Program Files"`:         both work


From my understanding the "," character in the command line has significant value in powershell. It is strange how this is only present in Win8, WinS2012, WinS2012R2.

**Comment by gfs** [comment]
It's very strange. Powershell should work so thanks for your report. I think it's fine to go with caret delimiters and just sidestep this while windows 8 weirdness

-------- Original Message --------
