### ISSUE TITLE
Extra path component while unzipping Asa-linux-2.2.47.tar.gz

### ISSUE THREAD

**Issue by jacobmsft** [microsoft/AttackSurfaceAnalyzer#474]
```
>tar xvzf Asa-linux-2.2.47.tar.gz
home/vsts/work/1/b/Asa-linux-2.2.47/
home/vsts/work/1/b/Asa-linux-2.2.47/Cli/
home/vsts/work/1/b/Asa-linux-2.2.47/Cli/createdump
home/vsts/work/1/b/Asa-linux-2.2.47/Cli/System.Xml.XmlDocument.dll
.
.
.

```

It would be great to have just Asa-linux-2.2.47/ and not the rest of the path, since we have to add this build artifact path to all the orchestrations that we add.

**Expected behavior**
```
>tar xvzf Asa-linux-2.2.47.tar.gz
Asa-linux-2.2.47/Cli/
Asa-linux-2.2.47/Cli/createdump
Asa-linux-2.2.47/Cli/System.Xml.XmlDocument.dll
.
.
.

```

**System Configuration (please complete the following information):**
 - OS: Linux
 - OS Version: *

**Comment by jacobmsft** [comment]
@daalcant

**Comment by gfs** [comment]
Ideally it should be `Asa-linux-2.2.47/Asa.exe` etc with no extra folder levels.
