### ISSUE TITLE
Error when opening results in Gui

### ISSUE THREAD

**Issue by gba8912** [microsoft/AttackSurfaceAnalyzer#475]
**Describe the bug**
Error is results tab: "An error occurred while processing your request" "request ID:00-295b95ffc39b77418df37c9eceb7cce5-c18116848eef0d43-00

**To Reproduce**
1.Run a new Scan
2. Check results tab

**Expected behavior**
Should be able to view result of scan

**Screenshots**
Attached screenshot

**System Configuration (please complete the following information):**
 - OS: Windows 10 & Server 2019
 - OS Version: 1903
 - Application Version: 2.2.47
 - CLI or GUI: GUI

**Additional Context**
Hello, I have been tasks to research this program for potential use. I have run into this error with both Win 10 and server 2019. I also tried running Asa in the built in admin account and got same error. 
![asa error](https://user-images.githubusercontent.com/66439049/83798935-04312180-a673-11ea-9719-cd3c2e3d68ee.JPG)

**Comment by gfs** [comment]
Thanks for your report. 

I'm excited to hear that ASA might be useful to you and sorry you're having this issue. 

I am able to reproduce this. I'll look today for when this regression was introduced, hope to have a fix by tomorrow.

**Comment by gba8912** [comment]
Thanks very much! I am glad it wasn't just me.

regards,

Gabriel

**Comment by gfs** [comment]
Build is running now that should fix this. New version should be available to download in the next hour. 

If you have any feedback about the Gui we have a work item to track a rewrite planned for this year. https://github.com/microsoft/AttackSurfaceAnalyzer/issues/316

If you plan to use this in a scripted manner you might want to check out running it directly from the Cli as well.

**Comment by gfs** [comment]
Sorry, looks like we've having issues with the build pipeline.  I will investigate tomorrow and get a build out.

**Comment by gba8912** [comment]
Thanks Gabe, I will watch for an update.

**Comment by gfs** [comment]
Hot off the presses, try 2.2.51.

https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.2.51%2B79843c10c8

**Comment by gba8912** [comment]
it works! thanks for your help and contributions.

**Comment by gba8912** [comment]
Sorry to bother again. I ran a scan, installed firefox, and ran another
scan. When i run results and select services, it says no change. Could you
share insight if maybe i am doing something wrong? I have a attached a
screenshot for reference.

**Comment by gfs** [comment]
It's possible I missed something in the Gui. I'll take a further look today.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by gfs** [comment]
I've tracked down the issue and it is a GUI only issue, but I don't have an immediate fix. Hoping to have one by Monday.

Workaround for now is to use the CLI.

**Comment by gba8912** [comment]
Thanks for the update! I think for ease of use and to easily show managers
whats going on, we would be using the gui. I will watch for an update next
week and keep playing around with it.

**Comment by gfs** [comment]
Try 2.2.53 now available.  I just personally tested removing a user and confirmed the result diff shows in the GUI.

**Comment by gba8912** [comment]
Thanks! ill give it a try today and send results.
