### ISSUE TITLE
Running CLI version as non-admin doesn't provide adequate feedback

### ISSUE THREAD

**Issue by scovetta** [Microsoft/AttackSurfaceAnalyzer#5]
**Describe the bug**
If a user (on Windows, in my case) runs the CLI version as a standard user, they get a UAC popup from .NET Core Host. If I click 'yes', then another command window opens briefly and then closes automatically, and I'm left back at the command prompt without information about what went wrong.

**To Reproduce**
1. Start as a standard user.
2. Open a PowerShell console.
3. Run AttackSurfaceAnalyzerCli.exe
4. Witness the popup open and close.

**Expected behavior**
Either provide the user immediate feedback that they should run the CLI once they have elevated privileges, or on Windows, trigger a UAC popup and elevate privileges from there.

**Screenshots**
n/a

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - Application Version: 2.0.1-beta+50af283871

**Additional context**
n/a

**Comment by gfs** [comment]
Fixed in [2.0.14](https://github.com/Microsoft/AttackSurfaceAnalyzer/releases/tag/v2.0.14-beta).
