### ISSUE TITLE
Add a splash screen to the GUI

### ISSUE THREAD

**Issue by Guydalf** [microsoft/AttackSurfaceAnalyzer#50]
**Describe the bug**
The GUI can take several seconds to show the home page leaving the user wondering if it is working or not.

**To Reproduce**
1. Go to asa.exe
2. Click on asa.exe or Right Click to Run as administrator
3. Wait for something to appear/happen

**Expected behavior**
If possible, cut down the start up code before home is shown or display an intro start up window that will let the user know it is loading.

**Comment by gfs** [comment]
This is likely pretty difficult the current way we use Electron. But it could definitely be possible if we started modifying the ElectronNet host as well as the CLI.  It would mean us making more code contributions to Electron.NET in order to accomplish this.

**Comment by Guydalf** [comment]
In that case, let's continue stabilizing core features first and prioritize against upcoming enhancements lists.

**Comment by gfs** [comment]
I did some more digging and discovered that there is a provision for adding a splash screen in Electron.NET. It might be possible do to this without modifying the library we are using after all.

**Comment by Guydalf** [comment]
Nice.  I'll see about creating one.

**Comment by Guydalf** [comment]
![asasplash](https://user-images.githubusercontent.com/47648296/56870849-6e848680-69ca-11e9-9ba9-523c44c75697.png)
Something like this should do.  Again this is a nice to have so users are not lost wondering whether something has started during the loading which isn't horrible but enough to make one unsure.

**Comment by gfs** [comment]
So, to make this happen we do have to make additional changes to Electron.NET.  From my testing it only adds the splash for a second or two. But it has been pretty limited as I don't have the end to end working. 

I can do some more testing and get you a build with a splash, but I think we need to go much simpler. I'd remove the subheader and the for more information line. There's no way they have time to copy that link or really read that full sentence I think.  I think we're fine on mockups, I can run with it from here.

**Comment by gfs** [comment]
Did some testing. So far I can get a splash screen that is an external URL to work, but the application itself crashes upon loading. Unfortunately looks like it'll be a larger time investment than I'd hoped.
