### ISSUE TITLE
Add Privacy Link To Home Page in GUI App

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#51]
**Describe the bug**
While a PRIVACY.md file exists in the program folder the user should be able to easily get to the notice details from the control where they are asked whether to allow telemetry or not.

**To Reproduce**
1. Go to application home page
2. See control for Enable / Disable Telemetry

**Expected behavior**
A visible link or instructions to find privacy details

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment]
Where should the link go?

**Comment by scovetta** [comment]
I think the link should go to PRIVACY.md on GitHub, so "https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/master/PRIVACY.md". Or we could go to the one associated with the commit of the build (e.g. "https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/v2.0.59-beta%2Bb585cf3fe9/PRIVACY.md").

@Guydalf Any preference there?
