### ISSUE TITLE
Zip Filename Length Prevents Extraction

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#52]
**Describe the bug**
The default zip file name is long enough to cause unzip issues that block some files from extraction and require the user to skip, cancel or restart the extraction but change the default foldername to install to.

Also changing the zip name and reattempting extraction fixes the issue.

**To Reproduce**
1. Go to the Release page
2. Click on a zip of the GUI version to download
3. Right click and chose to Extract all

**Expected behavior**
Use a shorter zip name to avoid the issue

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI:

**Additional Context**

**Comment by gfs** [comment]
This is really more of a Windows bug :p. But I went through an shortened the paths that we output for the artifacts by a bit.

AttackSurfaceAnalyzerCli-windows10

to

AsaCli-w10

**Comment by Guydalf** [comment]
Good.
