### ISSUE TITLE
[Authoring-Analysis-Rules] Page/File not found

### ISSUE THREAD

**Issue by haameeen** [microsoft/AttackSurfaceAnalyzer#542]
Many links are not opening under https://github.com/microsoft/AttackSurfaceAnalyzer/wiki/Authoring-Analysis-Rules. It gives 'Page not found'.

Examples(links provided in these sections):
- ...The Rules file is Deserialized into a RuleFile Object and processed by the Analysis engine against each object with a matching Result Type.
- ...The Rules section is a List of Rules. If...
- a Flag (ANALYSIS_RESULT_TYPE)...
- The Flag levels are defined in ANALYSIS_RESULT_TYPE. Results ...
- Rules are defined in a JSON file provided by the user or embedded in the build. The Rules file is Deserialized into a RuleFile Object and processed by the Analysis engine against each object with a matching Result Type....
... 

Basically, we're trying to understand the Analysis results, output and respective rules. What's not expected, and what's consider as issue or potential vulnerability.  etc.

Thanks!

**Comment by gfs** [comment]
Thanks for your report and good catch.  I fixed the dead links and they now point to the source code references.  We previously had some auto-generated documentation but that hasn't been updated in a while.

**Comment by gfs** [comment]
You can now view the API Reference again online.  For version 2.2 it is located at [https://microsoft.github.io/AttackSurfaceAnalyzer/v2.2/api/index.html](https://microsoft.github.io/AttackSurfaceAnalyzer/v2.2/api/index.html).
