### ISSUE TITLE
http 500 error version 68

### ISSUE THREAD

**Issue by pwpbarney** [microsoft/AttackSurfaceAnalyzer#552]
**Describe the bug**
Sorry this is more a request for help than a bug but I couldn't see where else to ask. I'm having problems getting this tool to run and I'm wondering if I need to install some prerequisite software?

For example if I run version 2.2.68+cbb75a2e27 with the gui I get HTTP 500 error.

Or I tried versions 68, 59 and 56 with the command `.\Asa.exe monitor` but I get a SqliteException when I try to export the result with `.\Asa.exe export-monitor`. (See screenshot).

I tried the gui again on version 56 and it completed both scans but it claimed there were no differences. I uninstalled a program and installed two new ones so something went wrong somewhere.

**To Reproduce**
Launch tool from administrative Powershell.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61739789/97019780-a54c4600-1548-11eb-9100-9025c43427ca.png)

**System Configuration (please complete the following information):**
 - OS: Windows 10
 - OS Version: 2004
 - Application Version: 68, 59 and 52
 - CLI or GUI: problems with both
I experienced issues on both bare metal and VM (windows 10 dev environment hyper-v image)

**Comment by gfs** [comment]
Hi pwpbarney,

Can you share what arguments you used for collection?

**Comment by gfs** [comment]
If you look at line 5 of the output you will see the warning message that no monitors have been defined.  This likely should actually be a fatal error not just a warning, but that indicates that you're not gathering any data.

To use the file system monitor run `asa monitor -f --runid YourRunId`.

I'm able to repro the issue with export monitor and I'll have a fix out soon.

**Comment by gfs** [comment]
I am able to also repro an issue with loading the gui in 68.  I'll have a fix for that soon as well.
