### ISSUE TITLE
Builds are being pushed with extraneous version numbers to Nuget

### ISSUE THREAD

**Issue by gfs** [microsoft/AttackSurfaceAnalyzer#553]
**Describe the bug**
https://www.nuget.org/packages/Microsoft.CST.AttackSurfaceAnalyzer.CLI/2.2.68-gcbb75a2e27

Nuget builds have extra version info at the end which causes nuget to classify them as prerelease and not offer them.

This was broken recently in the pipeline.

**Comment by daalcant** [comment]
Fixed
