### ISSUE TITLE
FileSystemCollector never ends in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by masty1982** [microsoft/AttackSurfaceAnalyzer#555]
There is a problem running "asa collect -a" in Ubuntu Linux 18.04 LTS and to be precise the file system collection. For some reason following commands never finish. I tested this with three different virtual machines that on different virtualization platforms (Oracle VirtualBox and XenCenter):
```
1. sudo .dotnet/tools/asa collect -a --overwrite --verbose --runid initial
2. sudo .dotnet/tools/asa collect -f --overwrite --verbose --directories /proc --runid initialproc
3. sudo .dotnet/tools/asa collect -f --overwrite --verbose --directories /sys --runid initialsys 
```

----
EDIT:
Installed Ubuntu Linux 20.04 to Oracle VirtualBox and more information was shown "Killed":
![asa_filesystemcollector_killed](https://user-images.githubusercontent.com/74306109/98945487-3e90cb80-24fb-11eb-8e1c-bfb0f2f4a37c.jpg)
----

When running without sys and proc directories, the file system collection finished in 15 mins:
`sudo ~/.dotnet/tools/asa collect -cfprsuFCl --overwrite --directories /bin^/boot^/dev^/etc^/home^/lib^/lib64^/lost+found^/media^/mnt^/opt^/root^/run^/sbin^/snap^/srv^/tmp^/usr^/var --runid excludeddirs`

**System Configuration:**
```
user@user-VirtualBox:~$ sudo .dotnet/tools/asa version
[15:12:47 INF] AttackSurfaceAnalyzer v.2.2.72+917982b04c
Asa 2.2.72+917982b04c

user@user-VirtualBox:~$ uname -a
Linux user-VirtualBox 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gfs** [comment]
Thanks for the report.  I'll push an update which skips /sys and /proc by default.

**Comment by masty1982** [comment]
Thanks for a quick reply and fix. 

I would also like to get a clarification to HTML report: "Results for the command line use option are written to a local HTML or JSON file, making it easy to include as part of your automated toolchain." Source: https://www.microsoft.com/security/blog/2019/05/15/announcing-new-attack-surface-analyzer-2-0/. 

I have not been able to get an HTML file with export-collect command. I only get a json.txt file. There is no documentation in the github related to HTML report but it is advertised in the blog post. If the HTML report is not supported could you point some way to convert JSON file to more human-readable format/equivalent to ASA 1.0 html report.

**Comment by gfs** [comment]
We switched to json only. There is a GUI you can run with 'asa Gui' it works with the same database so you can view your results there

**Comment by gfs** [comment]
I updated the default file system collector to skip proc and sys on linux systems.  New build should be coming out from the pipeline shortly if you want to give that a shot.  The default argument should now scan every root directory other than /sys and /proc

**Comment by gfs** [comment]
I also pushed a new change that will allow you to specifically exclude directories using the `--skip-directories` option so that you can explicitly provide `/` as the argument if you wish.  So for example `asa collect -f --directories / --skip-directories /proc,/sys,/mnt`, to skip `/proc` and `/sys` (to prevent stalls) and `/mnt` (for example).
