### ISSUE TITLE
Output Sarif

### ISSUE THREAD

**Issue by gfs** [microsoft/AttackSurfaceAnalyzer#564]
We should add an option (perhaps the new default and a bump to 2.4) to output sarif from guided mode and when exporting results. 

This needs to add a format Enum to ExportOptions to key off of, which would be set by GuidedMode and Exporting results, which the corresponding option also in the command line options and the blazor interface.

**Comment by eddynaka** [comment]
@yongyan-gh @shaopeng-gh, let's check if we can enable some argument to export a SARIF file

**Comment by eddynaka** [comment]
below, some guidance from @gfs :

https://github.com/microsoft/AttackSurfaceAnalyzer/blob/18768e7dac51e5f4c151d2186421f03ddcbf904e/Cli/AttackSurfaceAnalyzerClient.cs#L519

**Comment by gfs** [comment]
Also need to change https://github.com/microsoft/AttackSurfaceAnalyzer/blob/18768e7dac51e5f4c151d2186421f03ddcbf904e/Cli/AttackSurfaceAnalyzerClient.cs#L577

**Comment by shaopeng-gh** [comment]
I will take a look at this one.

**Comment by shaopeng-gh** [comment]
@gfs Hi I cloned the source code and took a look,
I see the program has a Export to Json function. 
which is serialization of a Dictionary<string,object>, and the object is mostly from "List<CompareResult>>"

Is the task to support export to .Sarif file, in addition to Json ? 
like user provide a switch --exportformat=Json/Sarif and we go to different code path to write file with the format.

If so, one question I have is how do we map each field in Json into each field in Sarif format file.
Do you some example Json files I can get some idea?

(btw I will need to add ref to Sarif SDK to generate Sarif file)

**Comment by gfs** [comment]
On Wed, Oct 6, 2021 at 12:44 AM, Shaopeng ***@***.***> wrote:

> ***@***.***(https://github.com/gfs) Hi I cloned the source code and took a look,
> I see the program has a Export to Json function.
> which is serialization of a Dictionary<string,object>, and the object is mostly from "List>"
>
> Is the task to support export to .Sarif file, in addition to Json ?
> like user provide a switch --exportformat=Json/Sarif and we go to different code path to write file with the format.

that’s the idea.

> If so, one question I have is how do we map each field in Json into each field in Sarif format file.
> Do you some example Json files I can get some idea?

I can generate one to send you today - but it’s just a serialization of a structure holding CompareResult objects, which each contain one or more CollectObjects.

I assume the vast majority of the fields from a compare result are not going to have a peer in the default Sarif and most of the info will go in the extra properties.

> (btw I will need to add ref to Sarif SDK to generate Sarif file)

yep that’s fine

**Comment by shaopeng-gh** [comment]
@gfs 
extra properties --- can you elaborate more

yes if you can send me a example json today that would be great. With that I will be able to take a look and to check with you and make sure we are in the same page which node in json map to which node in Sarif. Thanks!
like:
Json fieldA -> name
Json fielbB -> description

**Comment by shaopeng-gh** [comment]
@gfs I guess there will be much things in detail need to settle, I see the program have more than 1 type of Collector, and a extra type of real type monitor. will need to see where these info will fit in to the Sarif.
If your to be provided json can include nodes of them that would be great for us to discuss base on.

**Comment by shaopeng-gh** [comment]
@gfs thanks! A lot great info here, I will look into it :)

**Comment by shaopeng-gh** [comment]
Sarif:

{
  "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Attack Surface Analyzer",
          "rules": [
            {
              "id": "FILE_MODIFIED",
              "name": "FILE_MODIFIED"
            },
            {
              "id": "FILE_CREATED",
              "name": "FILE_CREATED"
            },
            {
              "id": "FILE_DELETED",
              "name": "FILE_DELETED"
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "FILE_MODIFIED",
          "level": "note",
          "message": {
            "text": "MODIFIED: C:\\Test\\Scan\\ToBeModified.txt"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/Test/Scan/ToBeModified.txt"
                }
              }
            }
          ],
          "properties": {
            "ResultType": "FILE",
            "ChangeType": "MODIFIED",
            "BaseRunId": "10/7/2021 9:21:33 PM-before",
            "CompareRunId": "10/7/2021 9:21:33 PM-after",
            "Base": {"ContentHash":null,"Created":"2021-10-08T04:18:58.206822Z","FileType":null,"Group":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Identity":"C:\\Test\\Scan\\ToBeModified.txt","IsDirectory":null,"IsExecutable":null,"IsLink":null,"LastModified":"2021-10-08T04:19:12.4498613Z","MacSignatureStatus":null,"Owner":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Path":"C:\\Test\\Scan\\ToBeModified.txt","Permissions":{"S-1-5-11":"Modify, Synchronize","S-1-5-18":"FullControl","S-1-5-32-544":"FullControl","S-1-5-32-545":"ReadAndExecute, Synchronize"},"PermissionsString":null,"SetGid":null,"SetUid":null,"SignatureStatus":null,"Size":5,"SizeOnDisk":null,"Target":null,"ResultType":1},
            "Compare": {"ContentHash":null,"Created":"2021-10-08T04:18:58.206822Z","FileType":null,"Group":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Identity":"C:\\Test\\Scan\\ToBeModified.txt","IsDirectory":null,"IsExecutable":null,"IsLink":null,"LastModified":"2021-10-08T04:22:04.3198988Z","MacSignatureStatus":null,"Owner":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Path":"C:\\Test\\Scan\\ToBeModified.txt","Permissions":{"NT AUTHORITY\\Authenticated Users":"Modify, Synchronize","NT AUTHORITY\\SYSTEM":"FullControl","BUILTIN\\Administrators":"FullControl","BUILTIN\\Users":"ReadAndExecute, Synchronize"},"PermissionsString":null,"SetGid":null,"SetUid":null,"SignatureStatus":null,"Size":13,"SizeOnDisk":null,"Target":null,"ResultType":1},
            "Diffs": [{"After":"2021-10-08T04:22:04.3198988Z","Before":"2021-10-08T04:19:12.4498613Z","Field":"LastModified"},{"After":{"NT AUTHORITY\\Authenticated Users":"Modify, Synchronize","NT AUTHORITY\\SYSTEM":"FullControl","BUILTIN\\Administrators":"FullControl","BUILTIN\\Users":"ReadAndExecute, Synchronize"},"Before":null,"Field":"Permissions"},{"After":null,"Before":{"S-1-5-11":"Modify, Synchronize","S-1-5-18":"FullControl","S-1-5-32-544":"FullControl","S-1-5-32-545":"ReadAndExecute, Synchronize"},"Field":"Permissions"},{"After":13,"Before":5,"Field":"Size"}],
            "Rules": [],
            "AnalysesHash": "yXvUiHy+rkKstAubfKrepSYhf7tGW6Fmpq72cvzjHu/IFkPu1P6FEstdy15fnGvxhAyIcIzdWFTILRTZ6wy0yA=="
          }
        },
        {
          "ruleId": "FILE_CREATED",
          "level": "note",
          "message": {
            "text": "CREATED: C:\\Test\\Scan\\NewlyCreated.txt"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/Test/Scan/NewlyCreated.txt"
                }
              }
            }
          ],
          "properties": {
            "ResultType": "FILE",
            "ChangeType": "CREATED",
            "BaseRunId": "10/7/2021 9:21:33 PM-before",
            "CompareRunId": "10/7/2021 9:21:33 PM-after",
            "Compare": {"ContentHash":null,"Created":"2021-10-08T04:22:11.5727345Z","FileType":null,"Group":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Identity":"C:\\Test\\Scan\\NewlyCreated.txt","IsDirectory":null,"IsExecutable":null,"IsLink":null,"LastModified":"2021-10-08T04:22:11.5727345Z","MacSignatureStatus":null,"Owner":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Path":"C:\\Test\\Scan\\NewlyCreated.txt","Permissions":{"NT AUTHORITY\\Authenticated Users":"Modify, Synchronize","NT AUTHORITY\\SYSTEM":"FullControl","BUILTIN\\Administrators":"FullControl","BUILTIN\\Users":"ReadAndExecute, Synchronize"},"PermissionsString":null,"SetGid":null,"SetUid":null,"SignatureStatus":null,"Size":0,"SizeOnDisk":null,"Target":null,"ResultType":1},
            "Diffs": [],
            "Rules": [],
            "AnalysesHash": "yXvUiHy+rkKstAubfKrepSYhf7tGW6Fmpq72cvzjHu/IFkPu1P6FEstdy15fnGvxhAyIcIzdWFTILRTZ6wy0yA=="
          }
        },
        {
          "ruleId": "FILE_DELETED",
          "level": "note",
          "message": {
            "text": "DELETED: C:\\Test\\Scan\\ToBeDeleted.txt"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/Test/Scan/ToBeDeleted.txt"
                }
              }
            }
          ],
          "properties": {
            "ResultType": "FILE",
            "ChangeType": "DELETED",
            "BaseRunId": "10/7/2021 9:21:33 PM-before",
            "CompareRunId": "10/7/2021 9:21:33 PM-after",
            "Base": {"ContentHash":null,"Created":"2021-10-08T04:18:43.2799276Z","FileType":null,"Group":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Identity":"C:\\Test\\Scan\\ToBeDeleted.txt","IsDirectory":null,"IsExecutable":null,"IsLink":null,"LastModified":"2021-10-08T04:18:43.2799276Z","MacSignatureStatus":null,"Owner":"S-1-12-1-1613650695-1152925323-3004084401-3676713700","Path":"C:\\Test\\Scan\\ToBeDeleted.txt","Permissions":{"S-1-5-11":"Modify, Synchronize","S-1-5-18":"FullControl","S-1-5-32-544":"FullControl","S-1-5-32-545":"ReadAndExecute, Synchronize"},"PermissionsString":null,"SetGid":null,"SetUid":null,"SignatureStatus":null,"Size":0,"SizeOnDisk":null,"Target":null,"ResultType":1},
            "Diffs": [],
            "Rules": [],
            "AnalysesHash": "yXvUiHy+rkKstAubfKrepSYhf7tGW6Fmpq72cvzjHu/IFkPu1P6FEstdy15fnGvxhAyIcIzdWFTILRTZ6wy0yA=="
          }
        }
      ],
      "columnKind": "utf16CodeUnits"
    }
  ]
}

**Comment by shaopeng-gh** [comment]
@gfs above is I drafted some code and generate an output for both json and sarif at the same time, just for a start point to discussion, let me know your inputs.

One issue I see is the rules are so different than the ones you have, in Sarif format there is a tool->driver->rules section and I guess it should contain the rules you have. Where can I find those? my generated json does not have any. 
Is it a pre-defined long list of all rules, or that I should loop through the CompareResult.Rules and dynamic generate?
If the CompareResult.Rules is empty like I have, should the Sarif file be empty?
Thanks!

**Comment by gfs** [comment]
> @gfs above is I drafted some code and generate an output for both json and sarif at the same time, just for a start point to discussion, let me know your inputs. 
> 
> (not sure how to format in GitHub, please copy to VS to see clearly)
> 

Here's a guide for GitHub markdown for the future. https://guides.github.com/features/mastering-markdown/

> 
> 
> One issue I see is the rules are so different than the ones you have, in Sarif format there is a tool->driver->rules section and I guess it should contain the rules you have. Where can I find those? my generated json does not have any. 
> 
> Is it a pre-defined long list of all rules, or that I should loop through the CompareResult.Rules and dynamic generate?
> 
> If the CompareResult.Rules is empty like I have, should the Sarif file be empty?
> 
> Thanks!
> 
> 
> 
> 
> 
> 
> 
>

**Comment by shaopeng-gh** [comment]
```json
{
  "results": {
    "FILE_CREATED": [
      {
        "Analysis": "DEBUG",
        "BaseRunId": "2021-10-14T16:40:08.6642182-07:00",
        "ChangeType": "CREATED",
        "Compare": {
          "ContentHash": "U5vuoQXdbgnk9XHXG35PFwb90oyl1iXPq63NYaMrIqpkQVU6X+ntJF7D57ZJFufpTXgPvR2zgqZu/anwz+wd2Q==",
          "Created": "2021-10-14T23:41:18.3939762Z",
          "Group": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Identity": "C:\\Test\\Scan2\\TestAddText.txt",
          "LastModified": "2021-10-14T23:43:53.0879739Z",
          "Owner": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Path": "C:\\Test\\Scan2\\TestAddText.txt",
          "Permissions": {
            "S-1-5-11": "Modify, Synchronize",
            "S-1-5-18": "FullControl",
            "S-1-5-32-544": "FullControl",
            "S-1-5-32-545": "ReadAndExecute, Synchronize"
          },
          "Size": 19,
          "ResultType": "FILE"
        },
        "CompareRunId": "2021-10-14T16:44:27.3260573-07:00",
        "Identity": "C:\\Test\\Scan2\\TestAddText.txt",
        "ResultType": "FILE",
        "Rules": [
          {
            "Name": ""
          }
        ]
      },
      {
        "Analysis": "WARNING",
        "BaseRunId": "2021-10-14T16:40:08.6642182-07:00",
        "ChangeType": "CREATED",
        "Compare": {
          "ContentHash": "3ptaDfkOhjUOM6QE2HoSCAasWmp9TR77AZVXRHniF8tWDXj1YT0rrjcxQAQmpOnxh31uVxfk0hqPyBbPWddeyA==",
          "Created": "2021-10-14T23:40:20.957942Z",
          "Group": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Identity": "C:\\Test\\Scan2\\TestAddExe.exe",
          "IsExecutable": true,
          "LastModified": "2021-10-13T03:05:24.3286411Z",
          "Owner": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Path": "C:\\Test\\Scan2\\TestAddExe.exe",
          "Permissions": {
            "S-1-5-11": "Modify, Synchronize",
            "S-1-5-18": "FullControl",
            "S-1-5-32-544": "FullControl",
            "S-1-5-32-545": "ReadAndExecute, Synchronize"
          },
          "Size": 726896,
          "ResultType": "FILE"
        },
        "CompareRunId": "2021-10-14T16:44:27.3260573-07:00",
        "Identity": "C:\\Test\\Scan2\\TestAddExe.exe",
        "ResultType": "FILE",
        "Rules": [
          {
            "ChangeTypes": [
              "CREATED",
              "MODIFIED"
            ],
            "Flag": "WARNING",
            "Platforms": [
              "WINDOWS"
            ],
            "ResultType": "FILE",
            "Description": "Flag when executables are created without DEP.",
            "Name": "Missing DEP"
          },
          {
            "ChangeTypes": [
              "CREATED",
              "MODIFIED"
            ],
            "Flag": "WARNING",
            "Platforms": [
              "WINDOWS"
            ],
            "ResultType": "FILE",
            "Description": "Flag when executables are created without ASLR.",
            "Name": "Missing ASLR"
          },
          {
            "ChangeTypes": [
              "CREATED",
              "MODIFIED"
            ],
            "Flag": "WARNING",
            "Platforms": [
              "LINUX",
              "MACOS",
              "WINDOWS"
            ],
            "ResultType": "FILE",
            "Description": "Flag when unsigned/incorrectly signed binaries are added.",
            "Name": "Unsigned binaries"
          }
        ]
      }
    ],
    "FILE_MODIFIED": [
      {
        "Analysis": "WARNING",
        "Base": {
          "ContentHash": "7QGAoQeCLD64FeGxlSoeW5eHcACmyBrT1HIv+YOGVi2Of6c88DR6+Uk1O2zemHCGXAeJrtc+COi8yqHrnpX8Zg==",
          "Created": "2021-10-14T23:36:58.0340629Z",
          "Group": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Identity": "C:\\Test\\Scan2\\TestModifyExe.exe",
          "IsExecutable": true,
          "LastModified": "2021-10-13T03:05:24.3286411Z",
          "Owner": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Path": "C:\\Test\\Scan2\\TestModifyExe.exe",
          "Permissions": {
            "S-1-5-11": "Modify, Synchronize",
            "S-1-5-18": "FullControl",
            "S-1-5-32-544": "FullControl",
            "S-1-5-32-545": "ReadAndExecute, Synchronize"
          },
          "Size": 726896,
          "ResultType": "FILE"
        },
        "BaseRunId": "2021-10-14T16:40:08.6642182-07:00",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ContentHash": "Qpr6h4sgWi9HvNaKn1kWmznUifwU+8Uw6RjczVpkzx/LlGSyJgEhQ9pkMe6sX3wo9gwLmZicOIelU2b9NncLiw==",
          "Created": "2021-10-14T23:36:58.0340629Z",
          "Group": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Identity": "C:\\Test\\Scan2\\TestModifyExe.exe",
          "IsExecutable": true,
          "LastModified": "2021-10-14T23:41:11.6798321Z",
          "Owner": "S-1-12-1-1613650695-1152925323-3004084401-3676713700",
          "Path": "C:\\Test\\Scan2\\TestModifyExe.exe",
          "Permissions": {
            "S-1-5-11": "Modify, Synchronize",
            "S-1-5-18": "FullControl",
            "S-1-5-32-544": "FullControl",
            "S-1-5-32-545": "ReadAndExecute, Synchronize"
          },
          "SignatureStatus": {},
          "Size": 343480,
          "ResultType": "FILE"
        },
        "CompareRunId": "2021-10-14T16:44:27.3260573-07:00",
        "Diffs": [
          {
            "After": "Qpr6h4sgWi9HvNaKn1kWmznUifwU+8Uw6RjczVpkzx/LlGSyJgEhQ9pkMe6sX3wo9gwLmZicOIelU2b9NncLiw==",
            "Before": "7QGAoQeCLD64FeGxlSoeW5eHcACmyBrT1HIv+YOGVi2Of6c88DR6+Uk1O2zemHCGXAeJrtc+COi8yqHrnpX8Zg==",
            "Field": "ContentHash"
          },
          {
            "After": "2021-10-14T23:41:11.6798321Z",
            "Before": "2021-10-13T03:05:24.3286411Z",
            "Field": "LastModified"
          },
          {
            "After": {},
            "Field": "SignatureStatus"
          },
          {
            "After": 343480,
            "Before": 726896,
            "Field": "Size"
          }
        ],
        "Identity": "C:\\Test\\Scan2\\TestModifyExe.exe",
        "ResultType": "FILE",
        "Rules": [
          {
            "ChangeTypes": [
              "CREATED",
              "MODIFIED"
            ],
            "Flag": "WARNING",
            "Platforms": [
              "LINUX",
              "MACOS",
              "WINDOWS"
            ],
            "ResultType": "FILE",
            "Description": "Flag when unsigned/incorrectly signed binaries are added.",
            "Name": "Unsigned binaries"
          },
          {
            "ChangeTypes": [
              "CREATED",
              "MODIFIED"
            ],
            "Flag": "WARNING",
            "Platforms": [
              "WINDOWS"
            ],
            "ResultType": "FILE",
            "Description": "Flag when executables are created without DEP.",
            "Name": "Missing DEP"
          },
          {
            "ChangeTypes": [
              "CREATED",
              "MODIFIED"
            ],
            "Flag": "WARNING",
            "Platforms": [
              "WINDOWS"
            ],
            "ResultType": "FILE",
            "Description": "Flag when executables are created without ASLR.",
            "Name": "Missing ASLR"
          }
        ]
      }
    ]
  },
  "metadata": {
    "compare-version": "2.4.9-alpha+18768e7dac",
    "compare-os": "WINDOWS",
    "compare-osversion": "Microsoft Windows NT 10.0.19043.0",
    "analyses-hash": "yXvUiHy+rkKstAubfKrepSYhf7tGW6Fmpq72cvzjHu/IFkPu1P6FEstdy15fnGvxhAyIcIzdWFTILRTZ6wy0yA=="
  }
}
```

**Comment by gfs** [comment]
> @gfs update: I have updated **_above_** Sarif, please review. 3. everything should be in artifacts node, and if it break/match a rule, it will have addition data in the results node saying which rule it breaks. if it break more than 1 rule, there will be more than 1 result node,

Okayu I think this looks fine.

> in the example the exe breaks both Unsigned and missing DEP. Sarif does not support result node without matching any rule, so in the example the txt file does not break any rule, so we can only find it in the artifacts node.

That is okay.

> 4. the result->message I current write as "{rule name}: identity (changetype)", this can be anything you like, let me know. 

Seems okay for now.

> 5. the Identity field of CompareResult class in AttackSurfaceAnalyzer, is it always a valid uri path? 

No.  It is a unique identifier in the context of that type of object on that system.  So for a File it is a URI, for a Registry Key is a registry path, for a Port it is the port number and protocol.  Many collected objects will not have a standard URI associated with them.  For FileSystemObject we use the `Path` property as the `Identity` https://github.com/microsoft/AttackSurfaceAnalyzer/blob/18768e7dac51e5f4c151d2186421f03ddcbf904e/Lib/Objects/FileSystemObject.cs#L50-L56

> 8. PR: #622 9. want to add some unit test for the method I added, which file should I put it, should I put in AsaAnalyzerTests.cs ?

Please just make a new test class.

**Comment by gfs** [comment]
This is merged.
