### ISSUE TITLE
Report.razor Null Exception

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#567]
**Describe the bug**
System.ArgumentOutOfRangeException null exception on Runs.Count in Report.razor 

**To Reproduce**
1. Start CLI with no previous runs stored
2. Open 'Report' page
3. System.ArgumentOutOfRangeException due to null Runs.Count

**Expected behavior**
Should have null check / handling

**Additional Context**
Issue exists in ASA 2.2 and 2.3 styling branch

**Comment by gfs** [comment]
This doesn't repro in the release/2.2 branch.
