### ISSUE TITLE
Upgrade to Latest Blazor Framework

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#569]
Upgrade to latest Blazor framework with some template changes:
https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0

**Comment by gfs** [comment]
This needs to be part of 2.3.

**Comment by gfs** [comment]
It is not difficult, I did it for our Blazor WebAssembly apps in a couple minutes.

**Comment by daalcant** [comment]
@gfs I gave it a shot but couldn't get the css isolation to work after applying changes, so assume I was doing something wrong.

**Comment by gfs** [comment]
When we sync I can take a closer look but it’s something we need to resolve so 2.3 can be .NET 5.0.
