### ISSUE TITLE
Wiki Update?

### ISSUE THREAD

**Issue by sunnysnair** [microsoft/AttackSurfaceAnalyzer#571]
Just started looking at "AttackSurfaceAnalyzer v.2.2.76" and can see some real good uses for ASA, with our product testing. I am not a developer by any means - so pardon my ignorance on some of the questions below.

1) It appears that the documentation here may perhaps require an update?
https://github.com/microsoft/AttackSurfaceAnalyzer/wiki/Authoring-Analysis-Rules#verifying-your-rules

- The only way I could verify a custom analysis rule that I am trying to put together, is by running the following:
asa verify --filename path/to/file.json

2) I am likely overlooking some important aspect of how to use a custom analysis rule - but after I create the 'file.json' do I have to ensure it is dropped into a specific folder, for ASA to consume/use?  My rule is a simple one wherein I am trying to flag when a system has a specific port opened up. I am attaching a copy of the JSON in case anyone can review and comment. I am looking for a specific port - thus the use of "CONTAINS" for type "Operation". (I tried to use "EQUALS", but, ASA was throwing an exception when I ran the verify on the file (when using "EQUALS").
[testrule.json.txt](https://github.com/microsoft/AttackSurfaceAnalyzer/files/5940115/testrule.json.txt)

Thanks!

**Comment by gfs** [comment]
1. Thanks for the catch.  The correct command is verify.
2. The correct operation enum for the Equals operation in 2.2 is `EQ`.  This changes in 2.3 to `EQUALS`

**Comment by gfs** [comment]
https://github.com/microsoft/AttackSurfaceAnalyzer/blob/68c0dfa092f2ca4561da2586930cf9048e103a67/Lib/Objects/Types.cs#L206-L276

This is the code containing the Enum for 2.2.
