### ISSUE TITLE
Sandbox page crashes with updated components

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#573]
**Branch**
da/asa-styling (Per ASA 2.3 upgrade work)

**Describe the bug**
The Sandbox page crashes after updating to new versions of components from OAT.Blazor.Components. Work is being done to remove the dependency on the OAT.Blazor.Components package, but the updated components are incompatible with the current ASA sandbox implementation.

**To Reproduce**
1. Run CLI from da/asa-styling branch
2. Navigate to Sandbox page
3. Attempt to create an object from the Types list

**Additional Context**
The OAT Sandbox changes can be referenced here:
https://github.com/microsoft/OAT/commit/f7936aa09df825a546fa653c7d6c80d2ae075712

Similar issues may also exist with the "Author" page as it contained the same dependency, but testing has not been conducted there yet.

**Comment by gfs** [comment]
Fixed.
