### ISSUE TITLE
Analyzing a Monitoring run causes a crash

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#574]
** Branch **
da/asa-styling (per ASA 2.3 upgrade)

**Describe the bug**
Performing analysis on a Monitoring run causes a crash.

**To Reproduce**
1. Run CLI on da/asa-styling branch
2. Navigate to the Monitor page
3. Complete a simple monitoring run. In my case, I monitored my Desktop directory and added/removed a file.
4. Navigate to the Analyze page
5. Select the completed run from step 3 in the first Run ID box
6. Ensure "Enable Analysis" is checked on (default)
7. Click "Start Analysis"
8. See error

**Expected behavior**
Analysis of the monitoring run should be successful.

**Additional Context**
1. Guided Mode fails when attempting to ONLY use a Monitor. May not be directly related.
2. Analysis does not fail when using Guided Mode with BOTH a FileSystem Collector AND a Monitor. May not be directly related.

**Comment by gfs** [comment]
Should be fixed in #570.
