### ISSUE TITLE
ProcessName not shown in analysis

### ISSUE THREAD

**Issue by masty1982** [microsoft/AttackSurfaceAnalyzer#579]
**Describe the bug**
ProcessName is not shown in Ports findings (ASA > Results > Ports).

**To Reproduce**
1. Open asa gui with admin rights
2. Scan the computer with asa (Select only Ports collector)
3. Open PowerShell window and open a new port:
    >$Listener = [System.Net.Sockets.TcpListener]9999;
    >$Listener.Start();
4. Check with netstat -abn that port 9999 is opened and see what process is listening this port (pwsh.exe)
5. Scan the computer again with asa (Select only Ports collector)
6. Open Results and compare these two baselines and select Ports
4. Port 9999 is shown but the ProcessName is empty

**Expected behavior**
ProcessName should be shown as it is available in netstat -abn. It is kind of essential information, which would help a lot in the analysis phase.

**Screenshots**
![image](https://user-images.githubusercontent.com/74306109/116969563-28501500-acbf-11eb-8e24-6ec4bd619a75.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 20H2 
 - Application Version: ASA 2.2.78
 - CLI or GUI: gui

**Additional Context**
-

**Comment by gfs** [comment]
Thanks for the report.  This should be being collected. I'll investigate this week.

**Comment by gfs** [comment]
This will be fixed in #582 for 2.3.  Gathering the process names requires running as administrator (it will fail to gather them silently if you run as regular user)

**Comment by masty1982** [comment]
I tried to test this:
```
C:\Users\masty> dotnet tool uninstall -g Microsoft.CST.AttackSurfaceAnalyzer.CLI
C:\Users\masty> dotnet tool install -g --version 2.3.142-beta Microsoft.CST.AttackSurfaceAnalyzer.CLI
warning NU1603: restore depends on Microsoft.CST.AttackSurfaceAnalyzer.CLI (>= 2.3.142-beta) but Microsoft.CST.AttackSurfaceAnalyzer.CLI 2.3.142-beta was not found. An approximate best match of Microsoft.CST.AttackSurfaceAnalyzer.CLI 2.3.142-beta-ge7cc357c64 was resolved.
You can invoke the tool using the following command: asa
Tool 'microsoft.cst.attacksurfaceanalyzer.cli' (version '2.3.142-beta-ge7cc357c64') was successfully installed.

```
But when I ran "asa gui" I got:
```
C:\Users\masty> asa gui
[09:52:49 INF] AttackSurfaceAnalyzer v.2.3.142-beta+e7cc357c64
[09:52:49 FTL] Database has schema version 10 but database has schema version 12.
[09:52:49 FTL] CouldNotSetupDatabase 
C:\Users\masty>

```

**Comment by masty1982** [comment]
@gfs 

Tested with 265-beta:
We collected information from Linux and then I used my Windows 10 laptop to check json file:  
`asa export-collect --disableanalysis --shards 1`

Json file did not include ProcessName information at all, see PORT_CREATED section below. Manually taking "netstat -anop" in Linux shows that port 8080 and 8081 is a java program. In Windows scans ProcessName is shown correctly. 

```
"PORT_CREATED": [
      {
        "BaseRunId": "baseline",
        "ChangeType": "CREATED",
        "Compare": {
          "Address": "::",
          "AddressFamily": "InterNetworkV6",
          "Identity": ":::InterNetworkV6:TCP:8080:",
          "Port": 8080,
          "Type": "TCP",
          "ResultType": "PORT"
        },
        "CompareRunId": "product",
        "Identity": ":::InterNetworkV6:TCP:8080:",
        "ResultType": "PORT"
      },
      {
        "BaseRunId": "baseline",
        "ChangeType": "CREATED",
        "Compare": {
          "Address": "::",
          "AddressFamily": "InterNetworkV6",
          "Identity": ":::InterNetworkV6:TCP:8081:",
          "Port": 8081,
          "Type": "TCP",
          "ResultType": "PORT"
        },
        "CompareRunId": "product",
        "Identity": ":::InterNetworkV6:TCP:8081:",
        "ResultType": "PORT"
      },
```

**Comment by gfs** [comment]
We actually use ss per recommendation from the man page for netstat.

It looks like this is an oversight and the data is indeed not being collected and I need to pass -p (and parse the new field)

https://www.binarytides.com/linux-ss-command/ has an example of the output.
