### ISSUE TITLE
Chocolist.txt referenced in user path not this repo

### ISSUE THREAD

**Issue by kilasuit** [microsoft/AttackSurfaceAnalyzer#589]
This line references a file that looks like it should be in this repo but isn't 
https://github.com/microsoft/AttackSurfaceAnalyzer/blob/0e3c7e1fa5ff50a328166b537547fab671bb1724/Tools/Docker/AsaDetonatorWindows/runall.ps1#L1 

Is this additional work that's needed to complete #464

**Comment by gfs** [comment]
Good catch. The problem is actually that runall.ps1 shouldn't be in the repository - Choco.txt was just a list of package names.

**Comment by gfs** [comment]
Runall.ps1 has been removed.
