### ISSUE TITLE
Sandbox: RegistryObject contains broken "Remove Dictionary Key And Value" button

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#598]
**Description:**
The RegistryObject type in the Sandbox page contains a "Remove Dictionary Key And Value" button that appears to do nothing.

**Expected behavior:**
The button should remove the selected Dictionary entry.

**To Reproduce:**

1. Run ASA, open GUI
2. Click Sandbox page
3. Select the RegistryObject type
4. Create the object
5. Click 'View' tab to view the object, expand its contents
6. Enter text into the two textboxes under "Permissions"
7. Click "Add Dictionary Key And Value" button, observe new entry added to dropdown box
8. Click "Remove Dictionary Key And Value" button, observe that the corresponding entry is not removed

**Configuration:**
 - ASA Application Version: v2.3.146-beta
 - OAT Application Version: 718b12bddf671984074aefe98e6789c4dd0c7b95

**Comment by gfs** [comment]
This will be fixed with https://github.com/microsoft/OAT/pull/79.
