### ISSUE TITLE
Sandbox: "Set to Null" doesn't persist on object creation

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#599]
**Description:**
In the Sandbox page, while creating an object and enabling the "Set to Null" checkbox on a property, the null value does not persist after the object is created and viewed.

**Expected behavior:**
The null value should persist on the property when viewed after object creation.

**To Reproduce:**

1. Run ASA, open GUI
2. Click Sandbox page
3. Select any type with a nullable property, e.g. WifiObject
4. Enable the "Set to Null" checkbox for a nullable property, e.g. SSID
5. Create the object
6. Click 'View' tab to view the object, expand its contents
7. Observe that the null value does not persist on the corresponding property

**Configuration:**
 - ASA Application Version: v2.3.146-beta
 - OAT Application Version: 718b12bddf671984074aefe98e6789c4dd0c7b95

**Comment by gfs** [comment]
Cannot observe.  None of the objects appear to have a nullable input parameter (and I believe that is by design in ASA).
