### ISSUE TITLE
Remove test 'output.html' from source tree

### ISSUE THREAD

**Issue by scovetta** [Microsoft/AttackSurfaceAnalyzer#6]
**Describe the bug**
A test [output.html](https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/master/Cli/output.html) is located in the source tree and should be removed.

**To Reproduce**
1. View [output.html](https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/master/Cli/output.html)

**Expected behavior**
Test files shouldn't be located in the source tree (a 'tests' directory, perhaps).

**Screenshots**
n/a

**System Configuration (please complete the following information):**
 - OS: n/a
 - OS Version: n/a
 - Application Version: n/a

**Additional context**
n/a

**Comment by gfs** [comment]
Fixed.
