### ISSUE TITLE
Sandbox: TargetParameterCountException when setting "Item" dropdown box value in TpmObject

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#600]
**Description:**
In the Sandbox page, when viewing a created TpmObject, under the "Commands" property, setting the value of the "Item" dropdown box causes an exception:
"System.Reflection.TargetParameterCountException: 'Parameter count mismatch.'"

Note that this is only applicable to the da/gui-updates branch and corresponding da/component-updates branch of OAT which contains an attempted fix for populating enum values in dropdown boxes.

**Expected behavior:**
The "Item" value should be set and not raise an exception.

**To Reproduce:**

1. Run ASA, open GUI
2. Click Sandbox page
3. Select the TpmObject type
4. Create the object
5. Click 'View' tab to view the object, expand its contents
6. Locate the "Commands" property, and the "Item" dropdown box underneath it
7. Attempt to change the dropdown box value, observe TargetParameterCountException

**Configuration:**
 - ASA Application Version: v2.3.146-beta
 - OAT Application Version: 718b12bddf671984074aefe98e6789c4dd0c7b95
 - ASA Branch: da/gui-updates
 - OAT Branch: da/component-updates

**Comment by gfs** [comment]
This is fixed.
