### ISSUE TITLE
Add it to winget

### ISSUE THREAD

**Issue by lnk3** [microsoft/AttackSurfaceAnalyzer#619]
**Describe alternatives you've considered**
I haven't found this software on the windows package manager repositories, maybe it is not been added since the product is not yet finished? I don't know actually if it is not finished since the version shown in the Tithub repo is already `2.0.0+`.

Idk, but I think it would be cool to have new tools you develop already available via the `winget` sw.
That is my opinion at least.
Please let me know if I stated something stupid.

**System Configuration (please complete the following information):**
* OS: Windows 11
* OS Version: OS Build 22000.176
* Application Version: 
* CLI or GUI: 

**Additional**
If by any change it was me at fault, who didn't found the name for this sw on the `winget` repos, maybe update the README to explain how to install it through that.

Thank you.

**Comment by gfs** [comment]
Thanks for the suggestion.  This isn't currently planned and it doesn't look like the process is automatable: https://docs.microsoft.com/en-us/windows/package-manager/package/repository so we are unlikely to pursue this.

If you want to install via the command line you can install the dotnet sdk via winget and then `dotnet tool install -g Microsoft.CST.AttackSurfaceAnalyzer.CLI`

**Comment by gfs** [comment]
This is also blocked by https://github.com/microsoft/winget-pkgs/issues/174 as we don't have an installer.
