### ISSUE TITLE
Broken link to Attack Surface Analyzer 1.0 in wiki

### ISSUE THREAD

**Issue by NiklasSch** [microsoft/AttackSurfaceAnalyzer#626]
The link (https://www.microsoft.com/en-us/download/details.aspx?id=24487) in the wiki to Attack Surface Analyzer 1.0 is not working anymore.
![image](https://user-images.githubusercontent.com/17223557/147346363-0b1edc59-eb7d-40a5-aeac-c9cd93b1e6c5.png)

Is there a new link to the Attack Surface Analyzer 1.0? I have searched a bit but did not find a suitable new link...

**Comment by gfs** [comment]
@scovetta was the take down of 1.0 intentional?

**Comment by scovetta** [comment]
@gfs Yes, ASA 1.0 was removed around Sept 2019 because the binaries were signed using a SHA-1 certificate, and the team that owned the code no longer exists. We should update the link.

@NiklasSch Is there specific functionality from v1 that would be helpful to have in v2?

**Comment by NiklasSch** [comment]
No, I wasn't looking for anything special from V1. I was just reading through the V2 repository/wiki a bit because I haven't used ASA V1 and V2 so far. During this, I noticed the broken link because I wanted to find out a bit more about V1.

@gfs I also noticed that the same link is used in the README.md. 

![image](https://user-images.githubusercontent.com/17223557/147496900-010c5cd6-c097-4d5b-a852-e83963e27a01.png)

**Comment by gfs** [comment]
Thanks @NiklasSch for catching that. I'll remove the dead links today.

**Comment by gfs** [comment]
Fixed in main and release/2.3 branches as well as wiki.

**Comment by mayrdhs** [comment]
The broken link is still listed in the wiki (https://github.com/microsoft/AttackSurfaceAnalyzer/wiki/FAQ's#can-i-still-access-the-attack-surface-analyzer-10-classic-version-of-the-tool).

**Comment by gfs** [comment]
Updated.
