### ISSUE TITLE
Windows Defender whitelisting in Wiki

### ISSUE THREAD

**Issue by mayrdhs** [microsoft/AttackSurfaceAnalyzer#632]
It took me some time to find the [entry](https://github.com/microsoft/AttackSurfaceAnalyzer/wiki/FAQ's#windows-defender-is-consuming-a-lot-of-cpu-when-running-asa) about whitelisting asa.exe in the FAQ. Before that a full scan took me around 45 minutes to complete because Windows Defender slowed everything down. Then I wasn't sure how to whitelist ASA because excluding the file (and/or the folder with the newest release version in it) didn't bring any improvement. Only after whitelisting the process "asa.exe" the scan time went down to roughly about 10 minutes. But I didn't want to exclude all processes called "asa.exe" from Windows Defender so a notice about the possibility to whitelist only the process in a specific path would be helpful (e.g. excluding "C:\Users\User\Downloads\ASA_win_2.3.272\asa.exe").
Also, since the impact of Windows Defender is very heavy, wouldn't it be a good idea to include a note about that in the Home section of the Wiki?

**Comment by gfs** [comment]
I added a note to check the FAQ to the main page of the wiki.

I've also updated the FAQ to indicate it is recommended to use the full path of the exe.
