### ISSUE TITLE
gitreleases.dev deprecated

### ISSUE THREAD

**Issue by mweibel** [microsoft/AttackSurfaceAnalyzer#634]
hi!

I'm the author of [gitreleases.dev](https://gitreleases.dev) and saw that you used gitreleases.dev somewhere in this repository. I can't find it in the code so maybe you removed the link already. 
Just a heads-up that gitreleases.dev will be shut down soon. GitHub has meanwhile added support for linking directly to assets:
https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

If you have no idea what this is about: nevermind and close the issue :)

Cheers
Michael

**Comment by gfs** [comment]
Hey there. I don't recall having used this but we may have in the past. 

I can't find any reference to it either currently.

Thanks for the heads up however!
