### ISSUE TITLE
OpenPortCollector does not work under all circumstances on Ubuntu

### ISSUE THREAD

**Issue by lpeter91** [microsoft/AttackSurfaceAnalyzer#649]
**Describe the bug**
There are certain cases when the `OpenPortCollector` will fail parsing the output of `ss`. The issue arises when there's only a single space separating the data of two columns. For me it's the data of the `State` and the `Recv-Q` columns. I don't know whether it can happen with other columns too, the formatting logic of `ss` is quite unclear. It actually seems to be affected by the terminal width too, at least when there's a tty attached, so it's even more uncertain what the ASA app "sees".

Partial example from an effectively empty Ubuntu 22.04 VM:

```
# ss -lnp | head
Netid State  Recv-Q Send-Q                              Local Address:Port        Peer Address:PortProcess                                                          
nl    UNCONN 0      0                                               0:530                     *                                                                     
nl    UNCONN 0      0                                               0:1559                    *                                                                     
nl    UNCONN 0      0                                               0:0                       *                                                                     
nl    UNCONN 0      0                                               0:1                       *                                                                     
nl    UNCONN 0      0                                               0:1559                    *                                                                     
nl    UNCONN 0      0                                               0:530                     *                                                                     
nl    UNCONN 0      0                                               0:1                       *                                                                     
nl    UNCONN 4352   0                                               4:5054                    *                                                                     
nl    UNCONN 768    0                                               4:0                       *   
```

This will break the parsing of the lines, I believe [here](https://github.com/microsoft/AttackSurfaceAnalyzer/blob/581baf9e089d64d729111c92df4e725c72986c1a/Lib/Collectors/OpenPortCollector.cs#L62), where it's expected that the column data is separated by at least 2 spaces.

**To Reproduce**
Reproduction is not trivial, as the output formatting of `ss` depends on a lot of not-so-well-known factors (see above).

**Expected behavior**
Detection of open ports should work even if `ss` columns are only separated by a single space.

**System Configuration**
```
root@ubuntu:~/ASA# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy
root@ubuntu:~/ASA# uname -a
Linux ubuntu 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~/ASA# ./Asa --version
[13:17:49 INF] AttackSurfaceAnalyzer v.2.3.277+40072595ef
Asa 2.3.277+40072595ef

```

**Comment by lpeter91** [comment]
Also leaving here my 2 cents:

I see that the "break at at least 2 whitespaces" logic was introduced earlier last year, I guess to not split the data of the `Local Address:Port` and `Peer Address:Port` columns, if they're space separated. 

Personally I'd probably (maybe?) go back to splitting even at single spaces, and then rejoin the appropriate columns when the line parts are of length 9. Though this is more of a heuristic approach based on my examination of the outputs of `ss`, rather than a scientific solution based on a deep understanding of the rendering logic of `ss`. I can't say how fragile this solution would be, and it would need to be confirmed working on different distros too.

I think the root of this issue is that the output of `ss` was not really meant for programmatic consumption. :)

**Comment by gfs** [comment]
Thanks for the report.

I haven't been able to find a suitably broadly supported more reliable replacement for manually parsing ss unfortunately. Originally I was using calls from the iproute2 package but that is even less broadly available and I didn't want to introduce a manual dependency if not absolutely needed. 

If you do have have a recommendation for a better way to get similar data on Linux I can investigate replacing ss.

For now, It looks like I'll have to account for the case where there are not two spaces. I should have time next week to look at this.

**Comment by lpeter91** [comment]
Yes, I understand, and I can't say that I can suggest a clearly better alternative. Some options that could be considered:

* I think parsing `/proc/net/{tcp|tcp6|...}`  should work on any Linux: https://www.kernel.org/doc/html/latest/networking/pro|c_net_tcp.html. Apart from some hex conversions the PID would need to be gathered by scanning `/proc/*/fd/*`. (Something like this: https://stackoverflow.com/a/30746415) This all might be too cumbersome.

  The kernel docs does say that the `/proc/net/tcp*` interface is deprecated, but there's little info to be found on the suggested alternative `tcp_diag`. I don't think `/proc/net/` is going anywhere in the foreseeable future.
* `lsof` is available on most Linuxes too. But then again, this method could suffer from similar output parsing issues. 
* While  I'm not sure what other tool you were using for this task form `iproute2`, I think `ss` is also a part of that package, so their availability should be the same. (Or maybe not on all distros?)

Thank you for looking into this!

**Comment by gfs** [comment]
Thanks for the suggestions.

It looks like tcp_diag uses sock_diag which actually checks the 'files' at proc for the information. From what I can see it looks like this is where ss is getting its info too. It might make the most sense just to parse the proc entries, but maybe it's possible to pinvoke the sock_diag calls? 

A very cursory search didn't turn up a wrapper library in C#, and as you found very little on using tcp or sock diag at all.

https://www.man7.org/linux/man-pages/man7/sock_diag.7.html

It looks like I was previously using lsof - this still currently being used in the Mac section. 

Offhand I don't recall why I switched to ss, but I'll try to track down the commit next week and see if I left a note.

**Comment by gfs** [comment]
I've found the commit and it is not explained why the change was made other than to fix an issue on ubuntu - but other changes were made at the same time to the collector as well to gather the process id (-p on ss). Removing the extra `\s` seems to fix the issue parsing the output you provided so I'll try reverting adding that extra \s to the split.

**Comment by lpeter91** [comment]
I can only drop a quick reply now, but as I mentioned earlier

> the "break at at least 2 whitespaces" logic was introduced earlier last year, I guess to not split the data of the Local Address:Port and Peer Address:Port columns, if they're space separated.

It's the case for sockets, which are also listed by `ss -lnp`. For these lines breaking at single spaces could be an issue. Unless these are filtered elsewhere, as they're not "open ports", strictly speaking. (A very quick look at the source tells me they're not filtered, but I could be easily wrong here.)

Example from my desktop:

```
# ss -lnp | egrep 'LISTEN|Netid' | head
Netid State  Recv-Q Send-Q                                      Local Address:Port        Peer Address:PortProcess                                                                                     
u_str LISTEN 0      4096                          /run/libvirt/virtlockd-sock 26200                  * 0    users:(("systemd",pid=1,fd=77))                                                            
u_str LISTEN 0      4096                    /run/libvirt/virtlockd-admin-sock 26202                  * 0    users:(("systemd",pid=1,fd=78))                                                            
u_str LISTEN 0      4096                           /run/libvirt/virtlogd-sock 26204                  * 0    users:(("systemd",pid=1,fd=79))                                                            
u_str LISTEN 0      4096                     /run/libvirt/virtlogd-admin-sock 26206                  * 0    users:(("systemd",pid=1,fd=80))                                                            
u_str LISTEN 0      20                        /run/libvirt/libvirt-admin-sock 26218                  * 0    users:(("libvirtd",pid=849,fd=3),("systemd",pid=1,fd=81))                                  
u_str LISTEN 0      1000                         /run/libvirt/libvirt-sock-ro 26220                  * 0    users:(("libvirtd",pid=849,fd=4),("systemd",pid=1,fd=82))                                  
u_str LISTEN 0      4096              /run/systemd/resolve/io.systemd.Resolve 25307                  * 0    users:(("systemd-resolve",pid=499,fd=15))                                                  
u_str LISTEN 0      4096                                  /tmp/.ICE-unix/2726 36969                  * 0    users:(("gnome-session-b",pid=2726,fd=12))                                                 
u_str LISTEN 0      4096                                 @/tmp/.ICE-unix/2726 36968                  * 0    users:(("gnome-session-b",pid=2726,fd=11)) 
```

Thanks for looking into it.

**Comment by gfs** [comment]
@lpeter91 thanks. that's definitely the reason. I think I have a better fix now in the same PR.

**Comment by lpeter91** [comment]
Thank you! I checked the fix, and it does seem to fix the original issue, but I think it accidentally broke process/PID extraction for some cases. Simple example:

```
# Start a webserver
# python -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...

# Check `ss` output in different terminal
# ss -lnp | grep 8000
tcp   LISTEN 0      5                                                                      0.0.0.0:8000             0.0.0.0:*    users:(("python",pid=21611,fd=3))
```

Now this doesn't fully match the current regex (does not produce 10 groups), basically due to the second `:`.

Going with the current approach the smallest diff fix is probably using the following slightly modified regex (not string-escaped):
`^([\S]+)\s+([\S]+)\s+([\S]+)\s+([\S]+)\s+([\S]+)[\s:]([\S]+)\s+([\S]+)(?:([\s:]([\S]+))?\s+([\S]+))?\s*$`

I tested it (only the regex, not the whole app) on a larger real example, which I attached here (should have than this earlier, sorry):
[ss.txt](https://github.com/microsoft/AttackSurfaceAnalyzer/files/8603865/ss.txt)

Also seems to be working with my earlier examples.

**Comment by gfs** [comment]
Thank you for rechecking. I can merge another fix with the proposed Regex today.

**Comment by gfs** [comment]
I think this is now fixed in the latest release. Reopen or create a new issue if you're still having trouble.
