### ISSUE TITLE
Export Rules to JSON still does not work

### ISSUE THREAD

**Issue by lacyvar** [microsoft/AttackSurfaceAnalyzer#675]
After repeating the steps described above
 (in the Issue#672),
 at the step "4. Click on the button `Export Rules to JSON`",
the result is a small file named "Asa-Rules.json" containing only the text "data:text/plain;charset=utf-8,".
Thus, it seems the function FileSaveAs gets the filename only and an empty fileContent, even the Rules were loaded before in step 3.

_Originally posted by @lacyvar in https://github.com/microsoft/AttackSurfaceAnalyzer/issues/672#issuecomment-1322656281_

**Comment by gfs** [comment]
I've merged the fix and tested the latest nuget package and it seems to be fixed. I'm able to load the default rules, export, clear and load and they validate without issues.
