### ISSUE TITLE
CLI simplification for runid

### ISSUE THREAD

**Issue by FritzSandsTM** [Microsoft/AttackSurfaceAnalyzer#69]
Since the run information in the database now contains a timestamp, the number of required command line parameters for data collection and comparison can be simplified.

(1) Data collection should not need a runid.  The collector can create a default runid based on the timestamp.  

(2) Data comparison should not need a designation for either runid, in the common case that the database contains exactly two runs.

So a minimal command usage would be

attacksurfaceanalyzer.exe config --reset-database
attacksurfaceanalyzer.exe collect -a
<install software>
attacksurfaceanalyzer.exe collect -a
attacksurfaceanalyzer.exe compare

**Comment by gfs** [comment]
I like this idea and it shouldn't be too difficult. I'll make this happen in the next few days.

**Comment by gfs** [comment]
I did this in a way that is a bit more expansive than proposed here.  The compare command run without arguments will now just use the latest two runs (as long as there are two runs). I implemented the same behavior for the export-collect command as well as for the monitor commands.

so
`attacksurfaceanalyzer.exe export-collect` is now also a value command.
