### ISSUE TITLE
How to change the port used

### ISSUE THREAD

**Issue by huntantr** [microsoft/AttackSurfaceAnalyzer#691]
**Describe the bug**
When attempting to run "asa gui" I get the following error.
[05:47:23 INF] AttackSurfaceAnalyzer v.2.3.297+8f3ee6911a
Unhandled exception. System.IO.IOException: Failed to bind to address http://localhost:5000.
This is a corporate machine and only specific ports are allowed.

**To Reproduce**
1. type "asa gui" 
Exception occurs due to the port being blocked. 

**Expected behavior**
The tool runs as expected.

**System Configuration (please complete the following information):**
 - OS: Windows 10
 - OS Version:  Windows 10 Pro 21H2 v19044.2846
 - Application Version:  v.2.3.297+8f3ee6911a
 - CLI or GUI: GUI

**Comment by gfs** [comment]
Hi @huntantr,

Thanks for the feedback! This isn't currently possible, but I've added this functionality to enable your scenario in #693. New version should be out later today with this functionality using `asa gui --port xxxx`

**Comment by gfs** [comment]
Fixed with #693.

**Comment by huntantr** [comment]
Thanks for the fast turn around.
