### ISSUE TITLE
Cannot detect registry created, deleted and modified by myself.

### ISSUE THREAD

**Issue by XYujie** [microsoft/AttackSurfaceAnalyzer#700]
Used command: `{asaPath} collect --registry --hives LocalMachine --runid Base001` 
* {asaPath} stands for the actual ASA.exe path

I've first run it as baseline scan and then created a registry key under "HKEY_LOCAL_MACHINE" and also a value in that key.

After that, run command: `{asaPath} collect --registry --hives LocalMachine --runid Pdt001` 
Finally run the command: `{asaPath} export-collect --firstrunid Base001  --secondrunid Pdt001 --outputpath {ExportPath}`
** {ExportPath} stands for the actual export path
I cannot find any object of REGISTRY_DELETED, REGISTRY_MODIFIED, REGISTRY_CREATED in JSON file. 
I have tried many times, delete existing keys and values or modify them, just not being scanned whatsoever.
Am I using the wrong hives option? or steps.
Please kindly give me some advice, I need your expertise.

I am using ASA_win_2.3.297 on Windows Server 2022 Standard.
Thank you in advance.

**Comment by gfs** [comment]
Hello, to confirm are you running ASA as administrator? A lot (most) of registry data isn't visible to standard user.

**Comment by XYujie** [comment]
Hello, I am running ASA as an administrator, and by waiting your reply I have run it without assigning any hives, and after baseline scan, I created some keys under LocalMachine, and then I run it again. 
I got a json file only contains some REGISTRY_MODIFIED objects, and all of them are from HKEY_CLASSES_ROOT.

**Comment by gfs** [comment]
Thanks for the confirmation. In that case the behavior you describe is not what I'd expect. 

Ill take some time to investigate this next week. I'll have to set up a VM with Server 2022 to see if it's an OS specific issue, I haven't noticed issues on standard Windows 10/11.

**Comment by XYujie** [comment]
Appreciate for that, and I am planning to do the same in Win10 to check if it is OS-specific issue, I'll let you know by this week.
To confirm, if I want to scan registry in LocalMachine, what is the correct arguments of `--hives`?  `HKEY_LOCAL_MACHINE` or `HkeyLocalMachine` or `LocalMachine`?

**Comment by XYujie** [comment]
I have run the ASA again with more information, hope this can be helpful for your investigation.
Here is the detail and steps I took.

**OS Info:**
Edition	            Windows 10 Enterprise LTSC
Version	            21H2
Installed on	‎    3/‎5/‎2022
OS build	            19044.1706
Experience	    Windows Feature Experience Pack 120.2212.4170.0


**ASA running Info in CMD(Run CMD as an Admin user):**
`C:\Users\root\Desktop\ASA_win_2.3.297\ASA_win_2.3.297>Asa.exe collect -r --runid BaselineScan001
[09:56:32 INF] AttackSurfaceAnalyzer v.2.3.297+8f3ee6911a
[09:56:32 INF] Begin BaselineScan001.
[09:56:32 INF] Starting 1 Collectors.
[09:56:37 INF] Starting RegistryCollector.
[09:58:04 INF] Completed RegistryCollector in 00h:01m:26s:628ms.

C:\Users\root\Desktop\ASA_win_2.3.297\ASA_win_2.3.297>Asa.exe collect -r --runid SecondScan001
[09:59:41 INF] AttackSurfaceAnalyzer v.2.3.297+8f3ee6911a
[09:59:41 INF] Begin SecondScan001.
[09:59:41 INF] Starting 1 Collectors.
[09:59:46 INF] Starting RegistryCollector.
[10:01:16 INF] Completed RegistryCollector in 00h:01m:30s:093ms.

C:\Users\root\Desktop\ASA_win_2.3.297\ASA_win_2.3.297>Asa.exe export-collect --firstrunid BaselineScan001 --secondrunid SecondScan001
[10:01:53 INF] AttackSurfaceAnalyzer v.2.3.297+8f3ee6911a
[10:01:53 INF] Comparing BaselineScan001 vs SecondScan001.
[10:02:03 INF] Completed Comparing in 00h:00m:09s:544ms.
[10:02:03 INF] Completed Analysis in 00h:00m:00s:070ms.
[10:02:03 INF] Output written to: C:\Users\root\Desktop\ASA_win_2.3.297\ASA_win_2.3.297\BaselineScan001_vs_SecondScan001_summary.json.txt`

**Manually created registry timing:**
After the BaselineScan001 completes, I created a Test registry key: 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\AfterBaseline`
And a registry name: `TestValue` under the test registry key.
Then I run the SecondScan001, I got a result file without any regitry creation info of above.

**JSON file I got:**
`{
  "results": {
    "REGISTRY_MODIFIED": [
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "18",
              "Version": "18"
            },
            "Before": {
              "Count": "0",
              "From": "16",
              "Version": "16"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
        "ResultType": "REGISTRY"
      },
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "28",
              "Version": "28"
            },
            "Before": {
              "Count": "0",
              "From": "26",
              "Version": "26"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
        "ResultType": "REGISTRY"
      },
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "28",
              "Version": "28"
            },
            "Before": {
              "Count": "0",
              "From": "26",
              "Version": "26"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{536A39A6-1444-4D54-91A4-1196BAF28709}",
        "ResultType": "REGISTRY"
      },
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "18",
              "Version": "18"
            },
            "Before": {
              "Count": "0",
              "From": "16",
              "Version": "16"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\AllUsers\\{D6416413-6137-46C3-B3CA-02C7C17F94C9}",
        "ResultType": "REGISTRY"
      },
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "28",
              "Version": "28"
            },
            "Before": {
              "Count": "0",
              "From": "26",
              "Version": "26"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
        "ResultType": "REGISTRY"
      },
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "22",
              "Version": "22"
            },
            "Before": {
              "Count": "0",
              "From": "20",
              "Version": "20"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
        "ResultType": "REGISTRY"
      },
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry64"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "28",
              "Version": "28"
            },
            "Before": {
              "Count": "0",
              "From": "26",
              "Version": "26"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry64_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{EDF8BF25-7D2D-4FEC-998D-50E27AC46B09}",
        "ResultType": "REGISTRY"
      },
      {
        "Analysis": "DEBUG",
        "Base": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "BaseRunId": "BaselineScan001",
        "ChangeType": "MODIFIED",
        "Compare": {
          "ResultType": "REGISTRY",
          "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Key": "HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
          "Permissions": {
            "BUILTIN\\Users": [
              "ReadKey",
              "-2147483648"
            ],
            "BUILTIN\\Administrators": [
              "FullControl",
              "268435456"
            ],
            "NT AUTHORITY\\SYSTEM": [
              "FullControl",
              "268435456"
            ],
            "S-1-3-0": [
              "268435456"
            ],
            "S-1-15-2-1": [
              "ReadKey",
              "-2147483648"
            ],
            "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": [
              "ReadKey",
              "-2147483648"
            ]
          },
          "ValueCount": 3,
          "View": "Registry32"
        },
        "CompareRunId": "SecondScan001",
        "Diffs": [
          {
            "After": {
              "Count": "0",
              "From": "22",
              "Version": "22"
            },
            "Before": {
              "Count": "0",
              "From": "20",
              "Version": "20"
            },
            "Field": "Values"
          }
        ],
        "Identity": "Registry32_HKEY_CLASSES_ROOT\\\\Local Settings\\Software\\Microsoft\\Windows\\CurrentVersion\\AppModel\\Deployment\\Package\\*\\S-1-5-21-3868626901-809077656-1508181376-1001\\{C2D7721E-3512-4198-AEFD-12E1DE356E69}",
        "ResultType": "REGISTRY"
      }
    ]
  },
  "metadata": {
    "compare-version": "2.3.297+8f3ee6911a",
    "compare-os": "WINDOWS",
    "compare-osversion": "Microsoft Windows NT 10.0.19044.0",
    "analyses-hash": "gtQ9YfSkO5gRqDAtswVRelP8315PdoGro5VYdejZCNl08ErSXgdCd2zSagl10r6BuLcXvzUw9q2Gp5MVZC1Jow=="
  }
}`

**Comment by gfs** [comment]
Thank you again for your detailed report, particularly the registry locations you were having trouble gathering.  I developed a fix in #701 that I believe will now resolve the issues you were experiencing with the Registry Collector. 
![image](https://github.com/microsoft/AttackSurfaceAnalyzer/assets/98900/4add1db5-1579-45e7-99ce-0f271abdd03c)

**Comment by XYujie** [comment]
@gfs 
Thanks for your improvement, and would you kindly tell me how to apply your fix? Should I download a particular stuff or something like that?

**Comment by gfs** [comment]
@XYujie 

We should be able to merge the PR today after which a new version will be published to nuget/as a zip.

**Comment by gfs** [comment]
PR has been merged. New release with the fix should be available in about an hour.

**Comment by XYujie** [comment]
Checked the new released version and it works well. Thank you for your quick fix!
