### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [microsoft/AttackSurfaceAnalyzer#702]
Does this work with Win 7?

Thanks

**Comment by scovetta** [comment]
@harryray33 We haven't tested ASA with Windows 7, so while it *might* work, there are no guarantees. Since Windows 7 isn't supported anymore, it isn't something that we'd test/validate against.

**Comment by gfs** [comment]
It is possible that it may work on Windows 7 SP1 using the .NET 6 SDK with some additional requirements as mentioned in the .NET 6 Supported OS list here: https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md, but as Mike mentioned we do not validate this scenario.

The .NET 7 and later builds will not work on Windows 7 as .NET 7 does not support Windows 7. https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md
