### ISSUE TITLE
No feedback to user when providing an invalid path

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#74]
**Describe the bug**
Enter an invalid folder for live monitoring and no error is indicated only that it completed the collection.  Minor bug but might be helpful to report as an error.

**To Reproduce**
1. Go to Scan page
2. Click on Live Monitor
3. Enter an invalid non-existent folder and click Collect Data
4. See error not reported but that Collection Completed.

**Expected behavior**
Minor bug but might be helpful to report as an error.

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment]
Thanks Guy. Will think about the best way to fix this.
