### ISSUE TITLE
Different algorithms (xxHash and MurMurHash) are used for file hashing

### ISSUE THREAD

**Issue by scovetta** [Microsoft/AttackSurfaceAnalyzer#8]
The [FileSystemUtils.cs](https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/master/Lib/Collectors/FileSystem/FileSystemUtils.cs#L42) and [WindowsFileSystemUtils.cs](https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/master/Lib/Collectors/FileSystem/WindowsFileSystemUtils.cs#L64) are using different algorithms to hash file contents. Since it's unlikely that anyone would need to do a diff between operating systems, it probably wouldn't cause a problem. (I'm also not sure if the FileSystemUtils.cs version is ever actually called.) Either way, we should be consistent. I'm not sure whether MurMurHash or xxHash would be faster here, but we should do a test and decide on one or the other.

**Comment by gfs** [comment]
I switched to Murmur for high performance with higher entropy - xxHash was having a bunch of collisions when gathering full registry or file system dumps. I thought I had removed all actual uses of xxHash, but it looks like this needs a bit more cleanup.

**Comment by rmandvikar** [comment]
> xxHash was having a bunch of collisions

@gfs: This link was quoted for xxHash having higher collisions than murmur. Just here to mention that it's not adding up for me. 

It seems you're using 32b instead of 64b (which is what the xxHash nuget lib you're using does in the call `xxHashFactory.Instance.Create()`). My guess is that you're using murmur 64b or 128b. Could you please confirm? HTH.

**Comment by gfs** [comment]
> > xxHash was having a bunch of collisions
> 
> 
> 
> @gfs: This link was quoted for xxHash having higher collisions than murmur. Just here to mention that it's not adding up for me. 
> 
> 
> 
> It seems you're using 32b instead of 64b (which is what the xxHash nuget lib you're using does in the call `xxHashFactory.Instance.Create()`). My guess is that you're using murmur 64b or 128b. Could you please confirm? I hope that helps you clear your confusion. 

That makes sense then. Looking back. I was using the default behavior of the System.Data.HashFunction.xxHash library and was not aware it had a configurable size. I was trying to optimize the time it took to hash strings that are ~all the paths on disk. 

My comment was intended to be about behavior in that specific scenario, not an in-depth analysis of the algorithms and was not intended to be a statement of "Murmur is better than xxHash".

This is the commit removes that code where you can see it uses the default, I haven't traced back to what version of the library that was using and what the size it sets is but I'll take your word it's 32.

https://github.com/microsoft/AttackSurfaceAnalyzer/commit/fb0994ecdfa15e486696effff8f5a076701be3bf

As for the key size for murmur, i was calling murmur128 which you can see in this commit:

https://github.com/microsoft/AttackSurfaceAnalyzer/blob/fb0994ecdfa15e486696effff8f5a076701be3bf/Lib/Utils/CryptoHelpers.cs

The current version (2.3) has actually switched to sha512 now based on the performance I saw in the benchmarks checked into the repo.

**Comment by rmandvikar** [comment]
> I haven't traced back to what version of the library that was using and what the size it sets is but I'll take your word it's 32.

Looking at your pr, you're using System.Data.HashFunction.xxHash 2.0.0 (the nuget ref wasn't remove in the pr by accident I think). 

see 
https://github.com/brandondahler/Data.HashFunction/blob/b9fdceb80f37a88928f3437c51825e4c5c715172/src/OpenSource.Data.HashFunction.xxHash/xxHashFactory.cs#L29-L30

and 

https://github.com/brandondahler/Data.HashFunction/blob/b9fdceb80f37a88928f3437c51825e4c5c715172/src/OpenSource.Data.HashFunction.xxHash/xxHashConfig.cs#L19

**Comment by gfs** [comment]
Thanks. That would be the likeliest reason then.

**Comment by gfs** [comment]
In case people are linking directly to the original comment I have also updated it with a clarification that provides the digest size context.
