### ISSUE TITLE
Collector UI State Doesn't Reset

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#92]
*Describe the bug**
Minor state issue with collectors after a completed scan which are not reset if the user navigates away to Results or Home including if the user selects Get Started button.  The scanID is cleared of the last value but not the collectors.

**Expected behavior**
Either change the Collect Data to "New" and keep both the scanID and collector state from the last run until they click New to clear it or once a user navigates away and returns to the Scan page clear the prior collection state.

**Screenshots**
![CollectStatusBugx](https://user-images.githubusercontent.com/47648296/55747650-97c87d00-59f1-11e9-875c-4519e25177f5.png)

**System Configuration (please complete the following information):**
 - OS: All
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI: GUI

**Comment by gfs** [comment]
I'm not sure I'm going to make any changes here.

The behavior shown above is exactly what they'd see if they stayed on the page without navigating away.

The difficulty is that if the user navigates away and comes back and the collectors are actually still running we need to show the correct status (and not allow them to start a new run).

The alternate behavior would be that they navigate back and, if the collectors are still running we still show that status, and if not it would just show the empty collect page. However, I think this creates a potential point of confusion for the user, as they may not be sure that the run they started before navigating away actually completed.

**Comment by Guydalf** [comment]
I see.  Then my suggestion is to keep the ScanID after the collection completes as well so that it is more clear and when of if the user wants to start a new one they will change the ScanID or be prompted to if they haven't for uniqueness etc.  Currently we have state but no scan id associated in the UI.  This is actually a better UX as they then know for certain that the last request was completed rather than emptying all state and is likely much less work to do.

**Comment by gfs** [comment]
If we keep the old scan id in the box it breaks the flow of automatically using the timestamps, but I think we can find a way to accomplish the same here. What about indicating what run the status applies to in the status box? We can redesign that box a bit anyway to make it more of its own UI element.

**Comment by gfs** [comment]
![image](https://user-images.githubusercontent.com/98900/55829226-0c1f2100-5ac3-11e9-9ed3-78a06abc761b.png)
Here's the new UX
