### ISSUE TITLE
Improve CLI help for expected values

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#99]
**Is your feature request related to a problem? Please describe.**
The CLI help provides command and subcommand lists do not indicate what values are expected in all cases leaving the user wondering what to provide and in some cases actually cases an error for incorrect values for example when enabling/disabling telemetry a 1 or 0 does not work and actually causes an exception to be thrown.

**Describe the solution you'd like**
Similar to other applications help provide example values i.e. "true|false"

**System Configuration (please complete the following information):**
* OS: [e.g. Windows]
* OS Version: [e.g. Windows 10 1803]
* Application Version: [e.g. 2.0.1-beta+50af283871]
* CLI or GUI: CLI

**Additional context**

**Comment by gfs** [comment]
I couldn't find any other examples of this other than the telemetry setting. but I have the PR up with just that change.
